# Generated by Django 5.2.12 on 2026-03-30 10:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Original debt amount', max_digits=18)),
                ('remaining_amount', models.DecimalField(decimal_places=2, help_text='Amount still owed (after partial repayments)', max_digits=18)),
                ('currency', models.CharField(default='EUR', help_text='ISO 4217 currency code (EUR, USD, RUB, etc.)', max_length=3)),
                ('description', models.TextField(blank=True, help_text='What is this debt for?')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft (Not Sent)'), ('PENDING_CONFIRMATION', 'Pending Confirmation'), ('ACTIVE', 'Active'), ('PARTIALLY_SETTLED', 'Partially Settled'), ('FULLY_SETTLED', 'Fully Settled'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=25)),
                ('confirmed_by_creditor_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by_debtor_at', models.DateTimeField(blank=True, null=True)),
                ('pgp_signature', models.TextField(blank=True, default='')),
                ('signed_payload', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebtRepayment',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount repaid', max_digits=18)),
                ('repayment_type', models.CharField(choices=[('MANUAL', 'Manual Repayment'), ('CYCLE_CLEARING', 'Cycle Clearing')], default='MANUAL', max_length=20)),
                ('clearing_exchange_id', models.CharField(blank=True, help_text='ULID of Exchange that cleared this debt (if type=CYCLE_CLEARING)', max_length=26, null=True)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
