# Generated by Django 5.2.12 on 2026-03-30 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debts', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='created_by',
            field=models.ForeignKey(help_text='Who initiated this debt record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts_created', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='debt',
            name='creditor',
            field=models.ForeignKey(help_text='Person who is owed money', on_delete=django.db.models.deletion.CASCADE, related_name='debts_receivable', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='debt',
            name='debtor',
            field=models.ForeignKey(help_text='Person who owes money', on_delete=django.db.models.deletion.CASCADE, related_name='debts_payable', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='debtrepayment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_repayments_created', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='debtrepayment',
            name='debt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='debts.debt'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['creditor', 'status'], name='debts_debt_credito_b74b9d_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['debtor', 'status'], name='debts_debt_debtor__00ca42_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['status', '-created_at'], name='debts_debt_status_6f9211_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['currency'], name='debts_debt_currenc_a41058_idx'),
        ),
        migrations.AddConstraint(
            model_name='debt',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='debt_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='debt',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_amount__gte', 0)), name='debt_remaining_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='debt',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_amount__lte', models.F('amount'))), name='debt_remaining_lte_amount'),
        ),
        migrations.AddIndex(
            model_name='debtrepayment',
            index=models.Index(fields=['debt', '-created_at'], name='debts_debtr_debt_id_aff691_idx'),
        ),
        migrations.AddIndex(
            model_name='debtrepayment',
            index=models.Index(fields=['clearing_exchange_id'], name='debts_debtr_clearin_f09e19_idx'),
        ),
        migrations.AddConstraint(
            model_name='debtrepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='repayment_amount_positive'),
        ),
    ]
