# Generated by Django 5.2.12 on 2026-03-30 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('market', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Enable AI-powered image analysis for marketplace items')),
                ('provider', models.CharField(choices=[('haiku', 'Claude Haiku 4.5 ($1/$5 per 1M)'), ('gpt-5-mini', 'GPT-5 mini ($0.50/$5 per 1M)'), ('gpt-5-nano', 'GPT-5 nano ($0.15/$1.50 per 1M)'), ('gemini-flash', 'Gemini 2.5 Flash ($0.30/$2.50 per 1M)'), ('gemini-flash-lite', 'Gemini 2.5 Flash-Lite ($0.10/$0.40 per 1M)')], default='gemini-flash-lite', help_text='AI provider to use for image analysis (vision + description)', max_length=20)),
                ('categorization_provider', models.CharField(choices=[('haiku', 'Claude Haiku 4.5 ($1/$5 per 1M)'), ('gpt-5-nano', 'GPT-5 nano ($0.15/$1.50 per 1M)'), ('gpt-5-mini', 'GPT-5 mini ($0.50/$5 per 1M)'), ('gemini-flash', 'Gemini 2.5 Flash ($0.30/$2.50 per 1M)'), ('gemini-flash-lite', 'Gemini 2.5 Flash-Lite ($0.10/$0.40 per 1M)'), ('same', 'Same as vision provider')], default='haiku', help_text='AI provider for category selection (uses cheaper models, sees ALL categories)', max_length=20)),
                ('use_single_request', models.BooleanField(default=False, help_text='When vision and categorization use same provider, combine into ONE request instead of two. Faster (~8s vs 13s). Supported: Claude, OpenAI, Gemini.', verbose_name='Use single request')),
                ('claude_api_key', models.CharField(blank=True, help_text='Anthropic API key for Claude Sonnet 4.5 (sk-ant-...)', max_length=200)),
                ('openai_api_key', models.CharField(blank=True, help_text='For GPT-5 models (sk-...)', max_length=200, verbose_name='OpenAI API key')),
                ('google_api_key', models.CharField(blank=True, help_text='For Gemini Flash (vision & categorization). Get from https://aistudio.google.com/apikey (format: AIza...)', max_length=200, verbose_name='Google Gemini API key')),
                ('total_requests', models.IntegerField(default=0, help_text='Total number of AI analysis requests')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Settings',
                'verbose_name_plural': 'AI Settings',
            },
        ),
        migrations.CreateModel(
            name='ZenithSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Enable Zenith AI assistant for this profile')),
                ('gitea_repo_name', models.CharField(blank=True, default='zenith-knowledge', help_text="Name of Gitea repository containing knowledge base (e.g., 'zenith-knowledge')", max_length=100)),
                ('gemini_api_key', models.CharField(blank=True, help_text='Personal Google Gemini API key. If empty, uses global AISettings key.', max_length=200)),
                ('system_prompt', models.TextField(blank=True, default='', help_text='Custom system prompt for Zenith. If empty, uses default.')),
                ('allow_contacts_access', models.BooleanField(default=True, help_text='Allow your contacts (partners) to ask your Zenith questions')),
                ('total_queries', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(help_text='Profile that owns this Zenith configuration', on_delete=django.db.models.deletion.CASCADE, related_name='zenith_settings', to='identity.profile')),
            ],
            options={
                'verbose_name': 'Zenith Settings',
                'verbose_name_plural': 'Zenith Settings',
            },
        ),
        migrations.CreateModel(
            name='AIAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('image_filename', models.CharField(blank=True, max_length=255)),
                ('image_size_original', models.IntegerField(help_text='Original image size in bytes')),
                ('image_size_compressed', models.IntegerField(help_text='Compressed image size in bytes')),
                ('vision_provider', models.CharField(default='unknown', help_text='Provider for vision analysis (claude, openai, google)', max_length=20)),
                ('categorization_provider', models.CharField(default='unknown', help_text='Provider for categorization (haiku, gpt-5-nano, etc.)', max_length=20)),
                ('language', models.CharField(default='en', help_text="User's preferred language code (en, ru, pt, etc.)", max_length=10)),
                ('suggested_category_confidence', models.FloatField(default=0.0)),
                ('suggested_title', models.TextField(blank=True)),
                ('suggested_description', models.TextField(blank=True)),
                ('suggested_price', models.JSONField(blank=True, help_text='Pricing option suggested by AI', null=True)),
                ('overall_confidence', models.FloatField(default=0.0)),
                ('vision_processing_time_ms', models.IntegerField(blank=True, help_text='Vision analysis time in milliseconds', null=True)),
                ('categorization_processing_time_ms', models.IntegerField(blank=True, help_text='Categorization time in milliseconds', null=True)),
                ('processing_time_ms', models.IntegerField(help_text='Total time taken for AI analysis in milliseconds (legacy)')),
                ('vision_input_tokens', models.IntegerField(blank=True, help_text='Vision: input tokens', null=True)),
                ('vision_output_tokens', models.IntegerField(blank=True, help_text='Vision: output tokens', null=True)),
                ('vision_cost_usd', models.DecimalField(blank=True, decimal_places=6, help_text='Vision: API cost', max_digits=10, null=True)),
                ('categorization_input_tokens', models.IntegerField(blank=True, help_text='Categorization: input tokens', null=True)),
                ('categorization_output_tokens', models.IntegerField(blank=True, help_text='Categorization: output tokens', null=True)),
                ('categorization_cost_usd', models.DecimalField(blank=True, decimal_places=6, help_text='Categorization: API cost', max_digits=10, null=True)),
                ('input_tokens', models.IntegerField(blank=True, help_text='DEPRECATED: Use vision_input_tokens', null=True)),
                ('output_tokens', models.IntegerField(blank=True, help_text='DEPRECATED: Use vision_output_tokens', null=True)),
                ('estimated_cost_usd', models.DecimalField(blank=True, decimal_places=6, help_text='DEPRECATED: Use vision_cost_usd + categorization_cost_usd', max_digits=10, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if analysis failed')),
                ('vision_request_prompt', models.TextField(blank=True, help_text='Full prompt sent to vision AI (for debugging)')),
                ('vision_response_raw', models.TextField(blank=True, help_text='Raw JSON response from vision AI')),
                ('categorization_request_prompt', models.TextField(blank=True, help_text='Full prompt sent to categorization AI')),
                ('categorization_response_raw', models.TextField(blank=True, help_text='Raw JSON response from categorization AI')),
                ('user_accepted_category', models.BooleanField(blank=True, help_text='Did user keep the suggested category?', null=True)),
                ('user_accepted_title', models.BooleanField(blank=True, help_text='Did user keep the suggested title?', null=True)),
                ('user_accepted_price', models.BooleanField(blank=True, help_text='Did user keep the suggested price?', null=True)),
                ('final_item', models.ForeignKey(blank=True, help_text='Item created after this analysis (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.item')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analyses', to='identity.profile')),
                ('suggested_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.category')),
            ],
            options={
                'verbose_name': 'AI Analysis Log',
                'verbose_name_plural': 'AI Analysis Logs',
                'indexes': [models.Index(fields=['-created_at'], name='parahub_aia_created_7173fc_idx'), models.Index(fields=['vision_provider', '-created_at'], name='parahub_aia_vision__1a9ccd_idx'), models.Index(fields=['profile', '-created_at'], name='parahub_aia_profile_8ea170_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuotaUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('ai_analysis', 'AI Image Analysis')], db_index=True, max_length=50)),
                ('used_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('amount', models.IntegerField(default=1, help_text='Amount consumed (default 1 for count-based resources)')),
                ('metadata', models.JSONField(blank=True, help_text='Context: AI log_id, API endpoint, etc.', null=True)),
                ('account', models.ForeignKey(help_text='Quota per account (shared across all profiles)', on_delete=django.db.models.deletion.CASCADE, related_name='quota_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quota Usage Log',
                'verbose_name_plural': 'Quota Usage Logs',
                'indexes': [models.Index(fields=['account', 'resource_type', '-used_at'], name='parahub_quo_account_983955_idx'), models.Index(fields=['resource_type', '-used_at'], name='parahub_quo_resourc_00d7e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ZenithQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Question asked')),
                ('answer', models.TextField(blank=True, help_text="Zenith's response")),
                ('files_used', models.JSONField(default=list, help_text='List of .md files loaded as context')),
                ('processing_time_ms', models.IntegerField(blank=True, help_text='Time taken for Gemini API call', null=True)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('estimated_cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('querier', models.ForeignKey(blank=True, help_text='Profile who made the query (null if owner)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zenith_queries_made', to='identity.profile')),
                ('zenith_owner', models.ForeignKey(help_text='Profile whose Zenith was queried', on_delete=django.db.models.deletion.CASCADE, related_name='zenith_queries_received', to='identity.profile')),
            ],
            options={
                'verbose_name': 'Zenith Query Log',
                'verbose_name_plural': 'Zenith Query Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['zenith_owner', '-created_at'], name='parahub_zen_zenith__cc8920_idx'), models.Index(fields=['querier', '-created_at'], name='parahub_zen_querier_03ec4b_idx')],
            },
        ),
    ]
