# Generated by Django 5.2.15 on 2026-06-24 16:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parahub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='market_discount_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.20'), help_text="Liquidity discount applied to the AI-suggested market price before it is pre-filled into the listing form. 0.20 = anchor the asking price 20% below the model's raw estimate to favour faster sales; 0 = disabled. The seller can always edit the final price.", max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
    ]
