# Generated by Django 5.2.12 on 2026-03-30 10:09

import core.models
import django.core.validators
import django.db.models.deletion
import logistics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0002_initial'),
        ('identity', '0001_initial'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('price_sats', models.BigIntegerField()),
                ('passengers_count', models.PositiveSmallIntegerField(default=1)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('destination_stop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='geo.stop')),
                ('origin_stop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='geo.stop')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests', to='identity.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RideBooking',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('status', models.CharField(choices=[('OFFERED', 'Offered'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OFFERED', max_length=15)),
                ('driver_note', models.CharField(blank=True, max_length=500)),
                ('available_seats', models.PositiveSmallIntegerField(default=3)),
                ('matrix_room_id', models.CharField(blank=True, max_length=255)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_drives', to='identity.profile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='logistics.riderequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RideReview',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='logistics.ridebooking')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_reviews_received', to='identity.profile')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_reviews_given', to='identity.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('title', models.CharField(max_length=200)),
                ('size_category', models.CharField(choices=[('S', 'Small (envelope/book)'), ('M', 'Medium (shoebox)'), ('L', 'Large (backpack)'), ('XL', 'Extra Large (suitcase)')], max_length=2)),
                ('tracking_code', models.CharField(db_index=True, default=logistics.models.generate_tracking_code, help_text='Public code for QR/sharing (e.g. A3K9M2XP)', max_length=8, unique=True)),
                ('pickup_code', models.CharField(default=logistics.models.generate_pickup_code, help_text='One-time code shown only to receiver', max_length=6)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('AT_ORIGIN', 'At Origin Hub'), ('IN_TRANSIT', 'In Transit'), ('AT_HUB', 'At Intermediate Hub'), ('READY', 'Ready for Pickup'), ('DELIVERED', 'Delivered'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=15)),
                ('storage_fee_total', models.PositiveIntegerField(default=0, help_text='Accumulated storage fee in sats')),
                ('delivery_fee', models.PositiveIntegerField(default=0, help_text='Agreed carrier fee in sats')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-set from hub_max_days on deposit', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('current_hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_current', to='geo.establishment')),
                ('destination_hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_inbound', to='geo.establishment')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='market.item')),
                ('origin_hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_outbound', to='geo.establishment')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments_received', to='identity.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments_sent', to='identity.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarrierOffer',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('fee_sats', models.PositiveIntegerField(default=0, help_text="Carrier's price in sats")),
                ('status', models.CharField(choices=[('OFFERED', 'Offered'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OFFERED', max_length=15)),
                ('matrix_room_id', models.CharField(blank=True, max_length=255)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_offers', to='identity.profile')),
                ('from_hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.establishment')),
                ('to_hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.establishment')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_offers', to='logistics.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('DEPOSITED', 'Deposited at hub'), ('CARRIER_PICKUP', 'Carrier picked up'), ('ARRIVED', 'Arrived at hub'), ('READY', 'Ready for pickup'), ('DELIVERED', 'Delivered to receiver'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('NOTE', 'Note')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='identity.profile')),
                ('hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.establishment')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='logistics.shipment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='riderequest',
            index=models.Index(fields=['is_active', '-created_at'], name='logistics_r_is_acti_cc0dbf_idx'),
        ),
        migrations.AddIndex(
            model_name='riderequest',
            index=models.Index(fields=['passenger', 'is_active'], name='logistics_r_passeng_c7afe9_idx'),
        ),
        migrations.AddIndex(
            model_name='ridebooking',
            index=models.Index(fields=['request', 'status'], name='logistics_r_request_98c07b_idx'),
        ),
        migrations.AddIndex(
            model_name='ridebooking',
            index=models.Index(fields=['driver', 'status'], name='logistics_r_driver__426ee7_idx'),
        ),
        migrations.AddConstraint(
            model_name='ridereview',
            constraint=models.UniqueConstraint(fields=('booking', 'reviewer'), name='unique_ride_review'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['sender', 'status'], name='logistics_s_sender__bca0c0_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['receiver', 'status'], name='logistics_s_receive_c73aa5_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['current_hub', 'status'], name='logistics_s_current_8d097a_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status', '-created_at'], name='logistics_s_status_cb8ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='carrieroffer',
            index=models.Index(fields=['shipment', 'status'], name='logistics_c_shipmen_0d9ede_idx'),
        ),
        migrations.AddIndex(
            model_name='carrieroffer',
            index=models.Index(fields=['carrier', 'status'], name='logistics_c_carrier_b41040_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentevent',
            index=models.Index(fields=['shipment', 'created_at'], name='logistics_s_shipmen_99b352_idx'),
        ),
    ]
