# Generated by Django 5.2.12 on 2026-03-30 10:09

import core.models
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('target_id', models.CharField(db_index=True, help_text='ULID of the liked object', max_length=26)),
                ('target_type', models.CharField(db_index=True, help_text='Object type: item, profile, establishment, etc.', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectComment',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('object_id', models.CharField(db_index=True, help_text='ULID of the target entity', max_length=26)),
                ('text', models.TextField(max_length=2000)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObjectPhoto',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('object_id', models.CharField(db_index=True, help_text='ULID of the target: WorldObject, Item, Establishment, etc.', max_length=26)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnershipLog',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('object_id', models.CharField(db_index=True, help_text='ULID of the WorldObject', max_length=26)),
                ('action', models.CharField(choices=[('claim', 'Claimed'), ('transfer', 'Transferred')], max_length=10)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileMigration',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('from_hna', models.CharField(help_text='Source HNA (e.g. deploy@parahub.io)', max_length=255)),
                ('to_hna', models.CharField(blank=True, help_text='Destination HNA (e.g. andrey@perliev.com)', max_length=255)),
                ('from_node', models.CharField(max_length=255)),
                ('to_node', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('exported', 'Data Exported'), ('signed', 'Signed by Both'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('from_user_signature', models.TextField(blank=True, help_text='PGP signature from source profile')),
                ('to_user_signature', models.TextField(blank=True, help_text='PGP signature from destination profile')),
                ('from_node_signature', models.TextField(blank=True, help_text='Node PGP signature from source node')),
                ('to_node_signature', models.TextField(blank=True, help_text='Node PGP signature from destination node')),
                ('export_hash', models.CharField(blank=True, help_text='SHA256 of export ZIP', max_length=64)),
                ('git_commit_hash', models.CharField(blank=True, max_length=40)),
                ('continuity_proof', models.CharField(blank=True, choices=[('same_seed', 'Same BIP39 seed'), ('cross_signed', 'Cross-signed')], help_text='How identity continuity is proven', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('public_key', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('registry_git_url', models.URLField(blank=True, help_text="URL to node's federation registry git repo")),
                ('ws_federation_url', models.URLField(blank=True, help_text='WebSocket federation endpoint')),
                ('matrix_server', models.CharField(blank=True, help_text='Matrix homeserver domain', max_length=255)),
                ('pgp_fingerprint', models.CharField(blank=True, help_text='Node PGP key fingerprint', max_length=40)),
                ('trust_level', models.CharField(choices=[('local', 'Local (this instance)'), ('bootstrap', 'Bootstrap (founding nodes)'), ('peer', 'Verified Peer'), ('observed', 'Observed (unverified)')], default='local', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, help_text='Last federation heartbeat', null=True)),
                ('capabilities', models.JSONField(blank=True, default=list, help_text='Node capabilities list')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['attributes'], name='core_instan_attribu_1a8622_gin'), django.contrib.postgres.indexes.GinIndex(fields=['relations'], name='core_instan_relatio_78f0b4_gin')],
            },
        ),
    ]
