# Generated by Django 5.2.12 on 2026-03-30 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='objectcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='objectphoto',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_photos', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='ownershiplog',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_actions', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='ownershiplog',
            name='new_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='ownershiplog',
            name='previous_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='profilemigration',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migrations', to='identity.profile'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['target_id'], name='core_like_target__994687_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['profile', '-created_at'], name='core_like_profile_6a5b0e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('profile', 'target_id')},
        ),
        migrations.AddIndex(
            model_name='objectcomment',
            index=models.Index(fields=['object_id', 'created_at'], name='core_object_object__d62c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='objectphoto',
            index=models.Index(fields=['object_id', 'order'], name='core_object_object__e77f23_idx'),
        ),
        migrations.AddIndex(
            model_name='ownershiplog',
            index=models.Index(fields=['object_id', '-created_at'], name='core_owners_object__0fb7b4_idx'),
        ),
    ]
