# Generated by Django 5.2.12 on 2026-03-31 11:43

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('identity', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemigration',
            name='to_hna',
            field=models.CharField(blank=True, help_text='Destination HNA (e.g. andrey@para.sh)', max_length=255),
        ),
        migrations.CreateModel(
            name='ObjectFile',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('object_id', models.CharField(db_index=True, help_text='ULID of the target: Post, SitePage, etc.', max_length=26)),
                ('file', models.FileField(upload_to='files/%Y/%m/')),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.IntegerField()),
                ('order', models.IntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='identity.profile')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['object_id', 'order'], name='core_object_object__583ee1_idx')],
            },
        ),
    ]
