# Generated by Django 5.2.12 on 2026-03-31 16:37

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profilemigration_to_hna_objectfile'),
        ('identity', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectVideo',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('object_id', models.CharField(db_index=True, help_text='ULID of the target: Item, Post, Establishment, Profile, etc.', max_length=26)),
                ('peertube_uuid', models.UUIDField(db_index=True, help_text='PeerTube video UUID (source of truth)', unique=True)),
                ('peertube_url', models.URLField(help_text='Watch URL: https://video.parahub.io/w/{short_uuid}', max_length=512)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=512)),
                ('embed_url', models.URLField(blank=True, help_text='PeerTube embed URL for iframe', max_length=512)),
                ('hls_url', models.URLField(blank=True, help_text='HLS playlist URL for direct player', max_length=512)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False, help_text='True once PeerTube finishes transcoding')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_videos', to='identity.profile')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['object_id', 'order'], name='core_object_object__71a733_idx')],
            },
        ),
    ]
