# Generated by Django 5.2.12 on 2026-04-03 11:20

import core.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_objectvideo'),
        ('finance', '0002_initial'),
        ('identity', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectDistribution',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('object_id', models.CharField(db_index=True, help_text='ULID of the entity distributing revenue', max_length=26)),
                ('period_label', models.CharField(help_text="Period identifier, e.g. '2026-03'", max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('DISTRIBUTED', 'Distributed')], default='DRAFT', max_length=12)),
                ('merkle_root', models.CharField(blank=True, help_text='SHA256 Merkle root of all lines for audit', max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DistributionLine',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('share_percent', models.DecimalField(decimal_places=3, help_text='Snapshot of share at distribution time', max_digits=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=10)),
                ('payment', models.ForeignKey(blank=True, help_text='Lightning payment if paid via wallet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.payment')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_lines', to='identity.profile')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.objectdistribution')),
            ],
            options={
                'ordering': ['distribution', '-amount'],
            },
        ),
        migrations.CreateModel(
            name='ObjectShare',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('object_id', models.CharField(db_index=True, help_text='ULID of the target: Establishment, EnergyCell, etc.', max_length=26)),
                ('share_type', models.CharField(choices=[('EQUITY', 'Equity'), ('INVESTMENT', 'Investment'), ('REVENUE', 'Revenue right')], default='INVESTMENT', max_length=12)),
                ('share_percent', models.DecimalField(decimal_places=3, help_text='0.000 – 100.000%', max_digits=6)),
                ('invested_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount invested (for INVESTMENT type)', max_digits=12, null=True)),
                ('invested_currency', models.CharField(default='EUR', max_length=3)),
                ('invested_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='identity.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='objectdistribution',
            index=models.Index(fields=['object_id', 'status'], name='core_object_object__b53afe_idx'),
        ),
        migrations.AddIndex(
            model_name='objectdistribution',
            index=models.Index(fields=['object_id', '-created_at'], name='core_object_object__3a67f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='objectdistribution',
            constraint=models.UniqueConstraint(fields=('object_id', 'period_label'), name='unique_distribution_per_period'),
        ),
        migrations.AddIndex(
            model_name='distributionline',
            index=models.Index(fields=['distribution', 'status'], name='core_distri_distrib_a34dcc_idx'),
        ),
        migrations.AddIndex(
            model_name='distributionline',
            index=models.Index(fields=['profile', 'status'], name='core_distri_profile_5ee27b_idx'),
        ),
        migrations.AddConstraint(
            model_name='distributionline',
            constraint=models.UniqueConstraint(fields=('distribution', 'profile'), name='unique_line_per_profile'),
        ),
        migrations.AddIndex(
            model_name='objectshare',
            index=models.Index(fields=['object_id', 'share_type'], name='core_object_object__4e3b5d_idx'),
        ),
        migrations.AddIndex(
            model_name='objectshare',
            index=models.Index(fields=['profile', 'is_active'], name='core_object_profile_74f3b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='objectshare',
            constraint=models.UniqueConstraint(fields=('object_id', 'profile', 'share_type'), name='unique_share_per_profile_type'),
        ),
        migrations.AddConstraint(
            model_name='objectshare',
            constraint=models.CheckConstraint(condition=models.Q(('share_percent__gte', Decimal('0')), ('share_percent__lte', Decimal('100'))), name='share_percent_range'),
        ),
    ]
