# Generated by Django 5.2.12 on 2026-03-30 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barter', '0001_initial'),
        ('identity', '0001_initial'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeapproval',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_approvals', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='exchangeswap',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps', to='barter.exchange'),
        ),
        migrations.AddField(
            model_name='exchangeswap',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps_offering', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='exchangeswap',
            name='offered_item',
            field=models.ForeignKey(help_text='CREDIT item being offered', on_delete=django.db.models.deletion.CASCADE, related_name='swaps_offered', to='market.item'),
        ),
        migrations.AddField(
            model_name='exchangeswap',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps_receiving', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='exchangeswap',
            name='wanted_item',
            field=models.ForeignKey(help_text='DEBIT item being wanted', on_delete=django.db.models.deletion.CASCADE, related_name='swaps_wanted', to='market.item'),
        ),
        migrations.AddField(
            model_name='exchangeapproval',
            name='swap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='barter.exchangeswap'),
        ),
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['status', '-created_at'], name='barter_exch_status_ccffc3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangeswap',
            unique_together={('exchange', 'order')},
        ),
        migrations.AddIndex(
            model_name='exchangeapproval',
            index=models.Index(fields=['exchange', 'approved'], name='barter_exch_exchang_7a8120_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangeapproval',
            unique_together={('exchange', 'user')},
        ),
    ]
