# Generated by Django 5.2.12 on 2026-03-30 10:09

import core.models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0002_initial'),
        ('identity', '0001_initial'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('territory', django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('land', 'Land Plot'), ('office', 'Office'), ('dacha', 'Dacha/Country House'), ('garage', 'Garage'), ('other', 'Other')], default='house', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='identity.profile')),
                ('world_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='geo.worldobject')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('SENSOR', 'Sensor'), ('ACTUATOR', 'Actuator (e.g., Smart Lock)'), ('MESH_ROUTER', 'Mesh Network Router'), ('GATEWAY', 'Gateway'), ('TRACKER', 'GPS Tracker'), ('HA_DEVICE', 'Home Assistant Device')], max_length=15)),
                ('imei', models.CharField(blank=True, help_text='IMEI для GPS трекеров', max_length=20, null=True)),
                ('device_id', models.CharField(blank=True, help_text='ID устройства указанный пользователем', max_length=50, null=True)),
                ('traccar_device_id', models.IntegerField(blank=True, help_text='ID устройства в Traccar', null=True)),
                ('connection_info', models.JSONField(blank=True, default=dict)),
                ('tunnel_ip', models.GenericIPAddressField(blank=True, null=True, unique=True)),
                ('wg_public_key', models.CharField(blank=True, max_length=44, null=True)),
                ('wg_ip', models.GenericIPAddressField(blank=True, null=True, unique=True)),
                ('ygg_allowed_ips', models.JSONField(blank=True, default=list, help_text='IPv6 addresses allowed inbound from Yggdrasil')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('status_data', models.JSONField(blank=True, default=dict)),
                ('item_twin', models.OneToOneField(blank=True, limit_choices_to={'spec_type': 'IOT_DEVICE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iot_device_link', to='market.item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iot_devices', to='identity.profile')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='iot.property')),
            ],
        ),
        migrations.CreateModel(
            name='HAHome',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('access_token_encrypted', models.TextField()),
                ('ha_version', models.CharField(blank=True, max_length=20)),
                ('location_name', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Auth Error')], default='offline', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('sync_interval_seconds', models.IntegerField(default=60)),
                ('auto_import', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ha_homes', to='identity.profile')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ha_homes', to='iot.property')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TraccarUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traccar_user_id', models.IntegerField(unique=True)),
                ('traccar_username', models.CharField(max_length=128, unique=True)),
                ('traccar_password_encrypted', models.CharField(max_length=256)),
                ('traccar_api_token', models.CharField(blank=True, max_length=256, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traccar_account', to='identity.profile')),
            ],
            options={
                'db_table': 'iot_traccar_user',
            },
        ),
        migrations.CreateModel(
            name='TrackerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(db_index=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, help_text='Speed in km/h', null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('battery_level', models.SmallIntegerField(blank=True, null=True)),
                ('satellites', models.SmallIntegerField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_history', to='iot.iotdevice')),
            ],
            options={
                'db_table': 'iot_tracker_history',
            },
        ),
        migrations.CreateModel(
            name='TrackerLocation',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, help_text='Speed in km/h', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Direction 0-360', null=True)),
                ('accuracy', models.FloatField(blank=True, help_text='Accuracy in meters', null=True)),
                ('battery_level', models.IntegerField(blank=True, help_text='Battery 0-100%', null=True)),
                ('signal_type', models.CharField(blank=True, max_length=10, null=True)),
                ('satellites', models.IntegerField(blank=True, null=True)),
                ('device_timestamp', models.DateTimeField()),
                ('device', models.OneToOneField(limit_choices_to={'device_type': 'TRACKER'}, on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to='iot.iotdevice')),
            ],
            options={
                'db_table': 'iot_tracker_location',
            },
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('direction_id', models.SmallIntegerField(default=0)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ASSIGNED', max_length=10)),
                ('display_vehicle_id', models.CharField(blank=True, help_text='Vehicle ID shown to passengers', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_assignments', to='identity.profile')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignments', to='geo.transitdatasource')),
                ('device', models.ForeignKey(limit_choices_to={'device_type': 'TRACKER'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignments', to='iot.iotdevice')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignments', to='geo.route')),
            ],
        ),
        migrations.CreateModel(
            name='HAEntity',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('entity_id', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=50)),
                ('friendly_name', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('attributes_json', models.JSONField(default=dict)),
                ('last_changed', models.DateTimeField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('is_imported', models.BooleanField(default=False)),
                ('is_controllable', models.BooleanField(default=False)),
                ('energy_signal_role', models.CharField(blank=True, choices=[('SURPLUS_BOOL', 'Solar surplus on/off'), ('SURPLUS_POWER', 'Solar production (watts)'), ('SURPLUS_PRICE', 'Solar price (€/kWh)')], db_index=True, max_length=15, null=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='iot.hahome')),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ha_entity', to='iot.iotdevice')),
            ],
            options={
                'ordering': ['domain', 'friendly_name'],
                'constraints': [models.UniqueConstraint(fields=('home', 'entity_id'), name='unique_entity_per_home')],
            },
        ),
        migrations.CreateModel(
            name='MeshSubscription',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('client_ip', models.GenericIPAddressField()),
                ('client_mac', models.CharField(blank=True, max_length=17)),
                ('ln_payment_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ln_invoice', models.TextField()),
                ('amount_sats', models.BigIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gateway_device', models.ForeignKey(limit_choices_to={'device_type': 'MESH_ROUTER'}, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='iot.iotdevice')),
            ],
            options={
                'indexes': [models.Index(fields=['gateway_device', 'status', 'expires_at'], name='iot_meshsub_gateway_1998f9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_property_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='iotdevice',
            constraint=models.UniqueConstraint(condition=models.Q(('device_type', 'MESH_ROUTER')), fields=('device_id',), name='unique_mesh_router_device_id'),
        ),
        migrations.AddConstraint(
            model_name='hahome',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_ha_home_per_owner'),
        ),
        migrations.AddIndex(
            model_name='trackerlocation',
            index=models.Index(fields=['device', '-device_timestamp'], name='iot_tracker_device__f624ec_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleassignment',
            index=models.Index(fields=['device', 'date', 'status'], name='iot_vehicle_device__50afba_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleassignment',
            index=models.Index(fields=['data_source', 'date', 'status'], name='iot_vehicle_data_so_00b1ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['ASSIGNED', 'ACTIVE'])), fields=('device', 'date'), name='unique_active_device_date'),
        ),
    ]
