# Generated by Django 5.2.15 on 2026-07-02 18:31

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0008_profile_civic_opinion_consent_and_more'),
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='household_invite_token',
            field=models.CharField(blank=True, help_text='Invite link token for household members (civic polls audience); rotate to revoke', max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PropertyMember',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('role', models.CharField(choices=[('member', 'Member')], default='member', max_length=10)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='household_invites_sent', to='identity.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_memberships', to='identity.profile')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_members', to='iot.property')),
            ],
            options={
                'indexes': [models.Index(fields=['profile'], name='iot_propert_profile_8f2b65_idx')],
                'unique_together': {('property', 'profile')},
            },
        ),
    ]
