# Generated by Django 5.2.12 on 2026-03-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('currency', models.CharField(help_text='ISO 4217 currency code', max_length=3, primary_key=True, serialize=False)),
                ('rate_to_eur', models.DecimalField(decimal_places=8, help_text='Exchange rate: 1 EUR = X currency', max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'currency_exchange_rates',
            },
        ),
    ]
