# Generated by Django 5.2.12 on 2026-03-30 10:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('source', models.CharField(choices=[('WALLET_SEND', 'After wallet P2P send'), ('ADS_CAMPAIGN', 'Ads campaign listing fee'), ('MANUAL', 'Manual donation')], max_length=20)),
                ('source_amount_sats', models.BigIntegerField(help_text='Original transaction amount')),
                ('donation_amount_sats', models.BigIntegerField(help_text='Actual donation amount')),
                ('support_level_at_time', models.DecimalField(decimal_places=1, max_digits=4)),
                ('ln_payment_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped (0%)')], default='PENDING', max_length=10)),
            ],
            options={
                'db_table': 'finance_donation',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('amount_sats', models.BigIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('ln_invoice', models.TextField(blank=True)),
                ('ln_payment_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('ln_preimage', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
