# Generated by Django 5.2.12 on 2026-03-30 10:09

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_payments', to='identity.profile'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['profile', '-created_at'], name='finance_don_profile_89b7c0_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status', '-created_at'], name='finance_don_status_a843f6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=django.contrib.postgres.indexes.GinIndex(fields=['attributes'], name='finance_pay_attribu_4b3231_gin'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=django.contrib.postgres.indexes.GinIndex(fields=['relations'], name='finance_pay_relatio_b78d1e_gin'),
        ),
    ]
