# Generated by Django 5.2.12 on 2026-03-30 10:09

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('geo', '0002_initial'),
        ('identity', '0001_initial'),
        ('iot', '0001_initial'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='items',
            field=models.ManyToManyField(blank=True, help_text='Items being exchanged in this contract', related_name='contracts', to='market.item'),
        ),
        migrations.AddField(
            model_name='contract',
            name='subject_property',
            field=models.ForeignKey(blank=True, help_text='Property this contract pertains to (sale, rental, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='iot.property'),
        ),
        migrations.AddField(
            model_name='contract',
            name='world_object',
            field=models.ForeignKey(blank=True, help_text='WorldObject (building/POI) this contract pertains to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='geo.worldobject'),
        ),
        migrations.AddField(
            model_name='arbitrationverdict',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verdict', to='identity.contract'),
        ),
        migrations.AddField(
            model_name='contractreview',
            name='contract',
            field=models.ForeignKey(help_text='Contract being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='identity.contract'),
        ),
        migrations.AddField(
            model_name='profile',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='core.instance'),
        ),
        migrations.AddField(
            model_name='profile',
            name='invited_by',
            field=models.ForeignKey(blank=True, help_text='Profile that invited this user via invite link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_profiles', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='pgpkeyhistory',
            name='profile',
            field=models.ForeignKey(help_text='Profile that owns this key', on_delete=django.db.models.deletion.CASCADE, related_name='pgp_key_history', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnered_by', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='partner',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='contractreview',
            name='reviewed',
            field=models.ForeignKey(help_text='Profile being reviewed (the other party)', on_delete=django.db.models.deletion.CASCADE, related_name='contract_reviews_received', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='contractreview',
            name='reviewer',
            field=models.ForeignKey(help_text='Profile giving the review', on_delete=django.db.models.deletion.CASCADE, related_name='contract_reviews_given', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='contract',
            name='arbiter',
            field=models.ForeignKey(blank=True, help_text='Optional arbitrator for dispute resolution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_arbitrating', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='contract',
            name='arbitration_escalated_by',
            field=models.ForeignKey(blank=True, help_text='Profile that escalated the arbitration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_arbitrations', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='contract',
            name='arbitration_initiator',
            field=models.ForeignKey(blank=True, help_text='Profile that initiated arbitration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_arbitrations', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='contract',
            name='creator',
            field=models.ForeignKey(help_text='Profile that created the contract', on_delete=django.db.models.deletion.CASCADE, related_name='contracts_created', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='contract',
            name='partner',
            field=models.ForeignKey(help_text='Partner profile', on_delete=django.db.models.deletion.CASCADE, related_name='contracts_received', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='arbitrationverdict',
            name='arbiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdicts_given', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='arbiterprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arbiter_profile', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='profilenote',
            name='about',
            field=models.ForeignKey(help_text='Profile that this note is about', on_delete=django.db.models.deletion.CASCADE, related_name='notes_about', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='profilenote',
            name='owner',
            field=models.ForeignKey(help_text='Profile that created this note', on_delete=django.db.models.deletion.CASCADE, related_name='notes_created', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='profileverificationphoto',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_photo', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='psychprofile',
            name='profile',
            field=models.OneToOneField(help_text='Profile this psycho-informatics data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='psych_profile', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='socialrecovery',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialrecovery',
            name='trustee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trustee_for', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='verification',
            name='verified_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_verifications', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='verification',
            name='verifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_verifications', to='identity.profile'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['account', 'is_primary'], name='identity_pr_account_d98531_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('instance', 'local_name')},
        ),
        migrations.AddIndex(
            model_name='pgpkeyhistory',
            index=models.Index(fields=['profile', '-action_timestamp'], name='identity_pg_profile_67288b_idx'),
        ),
        migrations.AddIndex(
            model_name='pgpkeyhistory',
            index=models.Index(fields=['fingerprint'], name='identity_pg_fingerp_2a2e94_idx'),
        ),
        migrations.AddIndex(
            model_name='pgpkeyhistory',
            index=models.Index(fields=['profile', 'valid_until'], name='identity_pg_profile_8136b8_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['profile', 'added_at'], name='identity_pa_profile_86e2fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partner',
            unique_together={('profile', 'partner_profile')},
        ),
        migrations.AlterUniqueTogether(
            name='contractreview',
            unique_together={('contract', 'reviewer')},
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['creator', 'status', '-created_at'], name='identity_co_creator_fada44_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['partner', 'status', '-created_at'], name='identity_co_partner_250665_idx'),
        ),
        migrations.AddIndex(
            model_name='arbitrationverdict',
            index=models.Index(fields=['arbiter'], name='identity_ar_arbiter_875d76_idx'),
        ),
        migrations.AddIndex(
            model_name='arbiterprofile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['attributes'], name='identity_ar_attribu_cfc29d_gin'),
        ),
        migrations.AddIndex(
            model_name='arbiterprofile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['relations'], name='identity_ar_relatio_c7742e_gin'),
        ),
        migrations.AddIndex(
            model_name='profilenote',
            index=models.Index(fields=['owner', 'about'], name='identity_pr_owner_i_2561ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='profilenote',
            constraint=models.UniqueConstraint(fields=('owner', 'about'), name='unique_note_per_profile'),
        ),
        migrations.AddIndex(
            model_name='profileverificationphoto',
            index=models.Index(fields=['reconfirmation_needed'], name='identity_pr_reconfi_2d0fd9_idx'),
        ),
        migrations.AddIndex(
            model_name='psychprofile',
            index=models.Index(fields=['profile'], name='identity_ps_profile_bfb5ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialrecovery',
            unique_together={('account', 'trustee')},
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['verified_profile', 'is_active'], name='identity_ve_verifie_7240bb_idx'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['verifier', 'is_active'], name='identity_ve_verifie_b21b3c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='verification',
            unique_together={('verifier', 'verified_profile')},
        ),
    ]
