# Generated by Django 5.2.15 on 2026-06-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='kind',
            field=models.CharField(choices=[('SALE', 'Sale / one-off deal'), ('RENTAL', 'Rental (asset returns)')], db_index=True, default='SALE', help_text='SALE consumes the item on completion; RENTAL returns it to availability', max_length=10),
        ),
    ]
