# Generated by Django 5.2.15 on 2026-06-24 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_id_photo_private_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='notes',
        ),
    ]
