# Generated by Django 5.2.15 on 2026-06-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_remove_verification_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='document_format',
            field=models.CharField(default='html', help_text="Format of document_text: 'html' (TipTap) or 'markdown'", max_length=10),
        ),
        migrations.AddField(
            model_name='contract',
            name='document_text',
            field=models.TextField(blank=True, default='', help_text='Private contract body (HTML); blank for legacy hash-only/upload contracts'),
        ),
    ]
