# Generated by Django 5.2.15 on 2026-06-29 16:25

from django.db import migrations, models


def pseudonymous_names_stay_public(apps, schema_editor):
    """Existing PSEUDONYMOUS profiles keep their name public: their display_name is
    already a pseudonym (the intended public face), so gating it gives no privacy.
    PERSONAL profiles keep the new default (False) — privacy by default."""
    Profile = apps.get_model('identity', 'Profile')
    Profile.objects.filter(profile_type='PSEUDONYMOUS').update(name_public=True)


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_contract_document_format_contract_document_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name_public',
            field=models.BooleanField(default=False, help_text='If True, display_name (real name) is shown to everyone. If False (default for personal profiles), only the @handle is public; the real name is revealed to the owner and WoT-verified viewers. Trust on parahub is identity-linked, but the legal name is only needed at the moment of commitment (a signed contract), not at browse time.'),
        ),
        migrations.RunPython(pseudonymous_names_stay_public, migrations.RunPython.noop),
    ]
