# Generated by Django 5.2.15 on 2026-07-02 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0037_territory'),
        ('identity', '0007_name_public_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='civic_opinion_consent',
            field=models.BooleanField(default=False, help_text='Explicit GDPR Art. 9(2)(a) consent to pseudonymized storage of opinion votes'),
        ),
        migrations.AddField(
            model_name='profile',
            name='civic_opinion_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='residency_changed_at',
            field=models.DateTimeField(blank=True, help_text='Last residency change; 30-day cooldown guards against territory poll-shopping', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='residency_territory',
            field=models.ForeignKey(blank=True, help_text='Declared residency (any level; parish preferred). Private: used only for civic poll scoping.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='geo.territory'),
        ),
    ]
