# Generated by Django 5.2.15 on 2026-07-04 19:37
"""
State-only removal of the contract models, moved to the contracts app
(contracts.0001_initial). The identity_* tables stay in place and stay owned
by identity's earlier migration history — no database operations here.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0008_profile_civic_opinion_consent_and_more'),
        ('rental', '0006_alter_booking_contract'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(database_operations=[], state_operations=[
        migrations.RemoveField(
            model_name='arbitrationverdict',
            name='arbiter',
        ),
        migrations.RemoveField(
            model_name='arbitrationverdict',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='arbiter',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='arbitration_escalated_by',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='arbitration_initiator',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='items',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='subject_property',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='world_object',
        ),
        migrations.RemoveField(
            model_name='contractreview',
            name='contract',
        ),
        migrations.AlterUniqueTogether(
            name='contractreview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='contractreview',
            name='reviewed',
        ),
        migrations.RemoveField(
            model_name='contractreview',
            name='reviewer',
        ),
        migrations.DeleteModel(
            name='ArbiterProfile',
        ),
        migrations.DeleteModel(
            name='ArbitrationVerdict',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='ContractReview',
        ),
        ]),
    ]
