# Generated by Django 5.2.12 on 2026-03-31 11:43

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0002_initial'),
        ('identity', '0002_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(db_index=True, max_length=200)),
                ('content', models.TextField(help_text='Markdown source of truth')),
                ('content_html', models.TextField(blank=True, help_text='Pre-rendered HTML from Markdown')),
                ('excerpt', models.TextField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(default='en', help_text='ISO 639-1: pt, en, es, fr, de, ru', max_length=2)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('featured_image_id', models.CharField(blank=True, help_text='ObjectPhoto ULID', max_length=26)),
                ('pgp_signature', models.TextField(blank=True)),
                ('allow_comments', models.BooleanField(default=True)),
                ('allow_tips', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('comments_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(help_text='Always a person, even when posting on behalf of establishment', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='identity.profile')),
                ('establishment', models.ForeignKey(blank=True, help_text='If set, this is an org blog post', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='geo.establishment')),
                ('tags', models.ManyToManyField(blank=True, related_name='blog_posts', to='taxonomy.category')),
                ('translation_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='cms.post')),
            ],
            options={
                'ordering': ['-is_pinned', '-published_at', '-created_at'],
                'indexes': [models.Index(fields=['establishment', 'status', '-published_at'], name='cms_post_establi_b49207_idx'), models.Index(fields=['author', 'status', '-published_at'], name='cms_post_author__7b2ee5_idx'), models.Index(fields=['slug'], name='cms_post_slug_90607d_idx'), models.Index(fields=['language'], name='cms_post_languag_657b9f_idx'), models.Index(fields=['status', '-published_at'], name='cms_post_status_1de8ed_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('establishment__isnull', False)), fields=('establishment', 'slug'), name='unique_est_slug'), models.UniqueConstraint(condition=models.Q(('establishment__isnull', True)), fields=('author', 'slug'), name='unique_author_slug')],
            },
        ),
    ]
