# Generated by Django 5.2.12 on 2026-03-31 11:58

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        ('geo', '0002_initial'),
        ('identity', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('accent_color', models.CharField(default='#F5C518', help_text='Hex color', max_length=7)),
                ('hero_text', models.TextField(blank=True, help_text='Markdown hero section text')),
                ('hero_text_html', models.TextField(blank=True)),
                ('hero_image_id', models.CharField(blank=True, help_text='ObjectPhoto ULID', max_length=26)),
                ('nav_sections', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('custom_domain', models.CharField(blank=True, help_text='e.g. cafe-central.pt', max_length=253)),
                ('establishment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site', to='geo.establishment')),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site', to='identity.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, help_text='Markdown')),
                ('content_html', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('show_in_nav', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='cms.site')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['establishment'], name='cms_site_establi_340f63_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['profile'], name='cms_site_profile_3c5b19_idx'),
        ),
        migrations.AddIndex(
            model_name='sitepage',
            index=models.Index(fields=['site', 'order'], name='cms_sitepag_site_id_ae23a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='sitepage',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='unique_site_page_slug'),
        ),
    ]
