# Generated by Django 5.2.12 on 2026-03-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_site_sitepage_site_cms_site_establi_340f63_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='custom_domain_ssl_ready',
            field=models.BooleanField(default=False, help_text='SSL cert issued and nginx configured'),
        ),
        migrations.AddField(
            model_name='site',
            name='custom_domain_verified',
            field=models.BooleanField(default=False, help_text='CNAME verified pointing to parahub.io'),
        ),
        migrations.AlterField(
            model_name='site',
            name='custom_domain',
            field=models.CharField(blank=True, db_index=True, help_text='e.g. cafe-central.pt', max_length=253),
        ),
    ]
