# Generated by Django 5.2.12 on 2026-04-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_site_custom_domain_ssl_ready_and_more'),
        ('geo', '0002_initial'),
        ('identity', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='site',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('establishment__isnull', True), ('profile__isnull', False)), models.Q(('establishment__isnull', False), ('profile__isnull', True)), _connector='OR'), name='site_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(condition=models.Q(('custom_domain', ''), _negated=True), fields=('custom_domain',), name='unique_custom_domain'),
        ),
    ]
