# Generated by Django 5.2.12 on 2026-04-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_cms_audit_fixes'),
        ('geo', '0005_drop_trip_shape_column'),
        ('identity', '0002_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish_order',
            field=models.PositiveIntegerField(blank=True, help_text='Topic ordering for publish queue. PT+EN share the same number.', null=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['establishment', 'publish_order'], name='cms_post_establi_78b180_idx'),
        ),
    ]
