# Generated by Django 5.2.12 on 2026-04-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_post_publish_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepage',
            name='is_homepage',
            field=models.BooleanField(default=False, help_text='Render this page content on site root /'),
        ),
    ]
