# Generated by Django 5.2.12 on 2026-04-07 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_sitepage_is_homepage'),
        ('identity', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approved_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When OWNER/ADMIN marked this post ready to publish', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Profile that marked this post approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_posts', to='identity.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_order',
            field=models.PositiveIntegerField(blank=True, help_text='Strategic topic ordering (from editorial plan). PT+EN+RU share the same number. Used as display/sort hint, not enforced.', null=True),
        ),
    ]
