# Generated by Django 5.2.15 on 2026-06-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_post_approved_at_post_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subscribers_only',
            field=models.BooleanField(default=False),
        ),
    ]
