# Generated by Django 5.2.15 on 2026-07-04 19:37
"""
State-only move of Contract/ContractReview/ArbiterProfile/ArbitrationVerdict
from identity into this app (paired with identity.0009 and rental.0006).

Every model keeps its original identity_* db_table, so database_operations is
empty: the tables were created (and are still created on a fresh database) by
identity's migration history. Do NOT squash identity past 0009 without moving
the table creation here.

The RunPython step reclaims the django_content_type rows (app_label
identity -> contracts) so existing GenericFK rows (audit_log.TimestampProof,
audit_log.MatrixRoomReference, notifications.Activity) keep resolving. On a
fresh database the rows don't exist yet (post_migrate creates them directly
under 'contracts') and the step is a no-op.
"""

import core.models
import django.db.models.deletion
from django.db import migrations, models

# Tables holding GenericFK rows that may reference the moved models.
GENERIC_FK_TABLES = (
    ('audit_log_timestampproof', 'content_type_id'),
    ('audit_log_matrixroomreference', 'content_type_id'),
    ('activities', 'content_type_id'),
)
MOVED_MODELS = ('contract', 'contractreview', 'arbiterprofile', 'arbitrationverdict')


def _repoint_contenttypes(apps, schema_editor, old_label, new_label):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    db = schema_editor.connection.alias
    for model in MOVED_MODELS:
        old = ContentType.objects.using(db).filter(app_label=old_label, model=model).first()
        if old is None:
            continue
        dupe = ContentType.objects.using(db).filter(app_label=new_label, model=model).first()
        if dupe is not None:
            # A row under the new label already exists (auto-created by a
            # get_for_model call racing this migration). Keep the old row —
            # existing data points at it — absorb whatever references the dupe.
            with schema_editor.connection.cursor() as cursor:
                for table, column in GENERIC_FK_TABLES:
                    cursor.execute(
                        f'UPDATE {table} SET {column} = %s WHERE {column} = %s',
                        [old.pk, dupe.pk],
                    )
            dupe.delete()
        old.app_label = new_label
        old.save(update_fields=['app_label'])


def reclaim_contenttypes(apps, schema_editor):
    _repoint_contenttypes(apps, schema_editor, 'identity', 'contracts')


def revert_contenttypes(apps, schema_editor):
    _repoint_contenttypes(apps, schema_editor, 'contracts', 'identity')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('geo', '0003_shape_dedup_squashed_0038_alter_stoptime_stop'),
        ('identity', '0008_profile_civic_opinion_consent_and_more'),
        ('iot', '0002_property_household_invite_token_propertymember'),
        ('market', '0004_item_visibility'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(database_operations=[], state_operations=[
        migrations.CreateModel(
            name='ArbiterProfile',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Arbitration fee amount', max_digits=10, null=True)),
                ('fee_currency', models.CharField(default='EUR', help_text='Fee currency (ISO 4217)', max_length=3)),
                ('bio', models.TextField(blank=True, help_text='Arbiter biography/description')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this arbiter is currently available')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arbiter_profile', to='identity.profile')),
                ('specializations', models.ManyToManyField(blank=True, db_table='identity_arbiterprofile_specializations', help_text='Arbiter specialization categories', related_name='arbiter_profiles', to='taxonomy.category')),
            ],
            options={
                'db_table': 'identity_arbiterprofile',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('title', models.CharField(help_text='Contract title/description', max_length=255)),
                ('file_sha256', models.CharField(help_text='SHA256 hash of contract file (computed client-side)', max_length=64)),
                ('document_text', models.TextField(blank=True, default='', help_text='Private contract body (HTML); blank for legacy hash-only/upload contracts')),
                ('document_format', models.CharField(default='html', help_text="Format of document_text: 'html' (TipTap) or 'markdown'", max_length=10)),
                ('creator_signature', models.TextField(help_text='PGP signature of creator (signing canonical JSON)')),
                ('partner_signature', models.TextField(blank=True, help_text='PGP signature of partner (signing canonical JSON)', null=True)),
                ('status', models.CharField(choices=[('PENDING_PARTNER', 'Awaiting Partner Signature'), ('SIGNED', 'Signed by Both Parties'), ('COMPLETED', 'Completed (Work Done)'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING_PARTNER', max_length=20)),
                ('kind', models.CharField(choices=[('SALE', 'Sale / one-off deal'), ('RENTAL', 'Rental (asset returns)')], db_index=True, default='SALE', help_text='SALE consumes the item on completion; RENTAL returns it to availability', max_length=10)),
                ('creator_signed_at', models.DateTimeField(auto_now_add=True, help_text='When creator signed the contract')),
                ('partner_signed_at', models.DateTimeField(blank=True, help_text='When partner signed the contract', null=True)),
                ('creator_completed_at', models.DateTimeField(blank=True, help_text='When creator marked contract as completed', null=True)),
                ('partner_completed_at', models.DateTimeField(blank=True, help_text='When partner marked contract as completed', null=True)),
                ('arbitration_room_id', models.CharField(blank=True, help_text='Matrix room ID for arbitration discussion', max_length=255, null=True)),
                ('arbitration_initiated_at', models.DateTimeField(blank=True, help_text='When arbitration was initiated', null=True)),
                ('arbitration_level', models.SmallIntegerField(default=1, help_text='Arbitration level: 1=P2P, 2=Institutional (CAC), 3=Court')),
                ('arbitration_escalated_at', models.DateTimeField(blank=True, help_text='When arbitration was escalated to the next level', null=True)),
                ('arbiter', models.ForeignKey(blank=True, help_text='Optional arbitrator for dispute resolution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_arbitrating', to='identity.profile')),
                ('arbitration_escalated_by', models.ForeignKey(blank=True, help_text='Profile that escalated the arbitration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_arbitrations', to='identity.profile')),
                ('arbitration_initiator', models.ForeignKey(blank=True, help_text='Profile that initiated arbitration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_arbitrations', to='identity.profile')),
                ('creator', models.ForeignKey(help_text='Profile that created the contract', on_delete=django.db.models.deletion.CASCADE, related_name='contracts_created', to='identity.profile')),
                ('items', models.ManyToManyField(blank=True, db_table='identity_contract_items', help_text='Items being exchanged in this contract', related_name='contracts', to='market.item')),
                ('partner', models.ForeignKey(help_text='Partner profile', on_delete=django.db.models.deletion.CASCADE, related_name='contracts_received', to='identity.profile')),
                ('subject_property', models.ForeignKey(blank=True, help_text='Property this contract pertains to (sale, rental, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='iot.property')),
                ('world_object', models.ForeignKey(blank=True, help_text='WorldObject (building/POI) this contract pertains to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='geo.worldobject')),
            ],
            options={
                'db_table': 'identity_contract',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArbitrationVerdict',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('verdict_type', models.CharField(choices=[('FAVOR_CREATOR', 'In Favor of Creator'), ('FAVOR_PARTNER', 'In Favor of Partner'), ('PARTIAL', 'Partial (Split)'), ('DISMISSED', 'Dismissed')], help_text='Type of verdict', max_length=20)),
                ('summary', models.TextField(help_text="Arbiter's reasoning and decision summary")),
                ('amount_awarded', models.DecimalField(blank=True, decimal_places=2, help_text='Amount awarded (if applicable)', max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, help_text='Currency of amount awarded', max_length=3)),
                ('creator_arbiter_rating', models.SmallIntegerField(blank=True, help_text="Creator's rating of the arbiter (1-5)", null=True)),
                ('partner_arbiter_rating', models.SmallIntegerField(blank=True, help_text="Partner's rating of the arbiter (1-5)", null=True)),
                ('arbiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdicts_given', to='identity.profile')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verdict', to='contracts.contract')),
            ],
            options={
                'db_table': 'identity_arbitrationverdict',
            },
        ),
        migrations.CreateModel(
            name='ContractReview',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('rating', models.SmallIntegerField(help_text='Rating 1-5 stars')),
                ('comment', models.TextField(blank=True, help_text='Optional review comment')),
                ('contract', models.ForeignKey(help_text='Contract being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='contracts.contract')),
                ('reviewed', models.ForeignKey(help_text='Profile being reviewed (the other party)', on_delete=django.db.models.deletion.CASCADE, related_name='contract_reviews_received', to='identity.profile')),
                ('reviewer', models.ForeignKey(help_text='Profile giving the review', on_delete=django.db.models.deletion.CASCADE, related_name='contract_reviews_given', to='identity.profile')),
            ],
            options={
                'db_table': 'identity_contractreview',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['creator', 'status', '-created_at'], name='identity_co_creator_fada44_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['partner', 'status', '-created_at'], name='identity_co_partner_250665_idx'),
        ),
        migrations.AddIndex(
            model_name='arbitrationverdict',
            index=models.Index(fields=['arbiter'], name='identity_ar_arbiter_875d76_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contractreview',
            unique_together={('contract', 'reviewer')},
        ),
        ]),
        migrations.RunPython(reclaim_contenttypes, revert_contenttypes, elidable=False),
    ]
