# Generated by Django 5.2.12 on 2026-03-30 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGPKeyPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=40)),
                ('public_key', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('git_commit_hash', models.CharField(max_length=40)),
                ('revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ProofExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('full', 'Full Account Export'), ('contract', 'Single Contract Export'), ('debt', 'Single Debt Export'), ('verifications', 'Verifications Export')], max_length=50)),
                ('object_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_hash', models.CharField(max_length=64, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimestampProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=26)),
                ('data_hash', models.CharField(max_length=64, unique=True)),
                ('data_json', models.TextField(blank=True, null=True)),
                ('ots_proof', models.BinaryField(blank=True, null=True)),
                ('git_event_path', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('bitcoin_block', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_commit_hash', models.CharField(max_length=40, unique=True)),
                ('git_commit_file', models.TextField()),
                ('ots_proof', models.BinaryField(null=True)),
                ('stamped_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(null=True)),
                ('bitcoin_block', models.IntegerField(null=True)),
                ('event_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-stamped_at'],
                'indexes': [models.Index(fields=['git_commit_hash'], name='audit_batch_git_commit_idx'), models.Index(fields=['-stamped_at'], name='audit_batch_stamped_at_idx'), models.Index(fields=['verified_at'], name='audit_batch_verified_at_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatrixRoomReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=26)),
                ('room_id', models.CharField(max_length=255, unique=True)),
                ('event_id', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('purpose', models.CharField(choices=[('system_notifications', 'System Notifications'), ('dispute', 'Dispute Resolution'), ('proof_backup', 'Proof Backup')], max_length=50)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
