# Generated by Django 5.2.12 on 2026-03-30 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit_log', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('identity', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgpkeypublication',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgp_publications', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='proofexport',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_exports', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='timestampproof',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proofs', to='audit_log.auditbatch'),
        ),
        migrations.AddField(
            model_name='timestampproof',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='matrixroomreference',
            index=models.Index(fields=['content_type', 'object_id'], name='audit_log_m_content_9516e5_idx'),
        ),
        migrations.AddIndex(
            model_name='matrixroomreference',
            index=models.Index(fields=['room_id'], name='audit_log_m_room_id_d962e2_idx'),
        ),
        migrations.AddIndex(
            model_name='pgpkeypublication',
            index=models.Index(fields=['profile', '-published_at'], name='audit_log_p_profile_f1e0e8_idx'),
        ),
        migrations.AddIndex(
            model_name='pgpkeypublication',
            index=models.Index(fields=['fingerprint'], name='audit_log_p_fingerp_c40c02_idx'),
        ),
        migrations.AddIndex(
            model_name='proofexport',
            index=models.Index(fields=['profile', '-created_at'], name='audit_log_p_profile_aecf15_idx'),
        ),
        migrations.AddIndex(
            model_name='timestampproof',
            index=models.Index(fields=['content_type', 'object_id'], name='audit_log_t_content_2c995e_idx'),
        ),
        migrations.AddIndex(
            model_name='timestampproof',
            index=models.Index(fields=['data_hash'], name='audit_log_t_data_ha_2778b1_idx'),
        ),
    ]
