# Generated by Django 5.2.12 on 2026-04-09 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0002_initial'),
        ('identity', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiteaCommentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitea_comment_id', models.BigIntegerField(db_index=True, help_text="Gitea's internal comment ID")),
                ('gitea_repo', models.CharField(help_text='Full repo path, e.g. cms-editorial/parahub-associacao', max_length=200)),
                ('gitea_issue_number', models.PositiveIntegerField()),
                ('author_username', models.CharField(help_text='Gitea username at time of comment', max_length=100)),
                ('text', models.TextField(help_text='Full comment body at this version')),
                ('version', models.PositiveIntegerField(default=1, help_text='Increments on edit: v1=created, v2+=edited')),
                ('deleted_in_gitea', models.BooleanField(default=False, help_text='True if comment was later deleted in Gitea')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.profile')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['gitea_comment_id', 'version'], name='audit_log_g_gitea_c_420a82_idx'), models.Index(fields=['gitea_repo', 'gitea_issue_number'], name='audit_log_g_gitea_r_986b73_idx')],
            },
        ),
    ]
