# Generated by Django 5.2.15 on 2026-06-21 10:17

import core.models
import datetime
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import rental.models
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_initial'),
        ('market', '0002_delete_video'),
    ]

    operations = [
        # btree_gist enables the scalar `bookable` equality inside the GiST
        # exclusion constraint on Booking (no_double_booking). First use of a
        # Postgres exclusion constraint in this repo.
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Bookable',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('booking_mode', models.CharField(choices=[('RANGE', 'Date range (check-in/check-out)'), ('SLOTS', 'Recurring time slots')], default='RANGE', max_length=8)),
                ('timezone', models.CharField(default='Europe/Lisbon', help_text='IANA tz; availability/slots are interpreted in this local time', max_length=64)),
                ('min_duration', models.DurationField(blank=True, help_text='Minimum rental length', null=True)),
                ('max_duration', models.DurationField(blank=True, help_text='Maximum rental length', null=True)),
                ('buffer', models.DurationField(default=datetime.timedelta(0), help_text='Turnaround gap between bookings')),
                ('advance_window', models.DurationField(default=datetime.timedelta(days=90), help_text='How far ahead bookings are allowed')),
                ('confirmation', models.CharField(choices=[('AUTO', 'Auto-confirm'), ('REQUEST', 'Owner approves')], default='AUTO', max_length=8)),
                ('requires_contract', models.CharField(choices=[('NEVER', 'Never'), ('THRESHOLD', 'When asset warrants it'), ('ALWAYS', 'Always')], default='THRESHOLD', help_text='When a CONFIRMED booking should spawn a rental Contract (see .todo/rental.md)', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('item', models.OneToOneField(help_text="The rentable subject (must have a 'rent' pricing option)", on_delete=django.db.models.deletion.CASCADE, related_name='bookable', to='market.item')),
            ],
            options={
                'verbose_name': 'Bookable',
                'verbose_name_plural': 'Bookables',
            },
        ),
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('bookable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='rental.bookable')),
            ],
            options={
                'verbose_name': 'Availability exception',
                'verbose_name_plural': 'Availability exceptions',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('start', models.TimeField(default='09:00')),
                ('stop', models.TimeField(default='18:00')),
                ('slot_minutes', models.PositiveSmallIntegerField(default=60, help_text='Slot length for SLOTS mode (ignored for RANGE)')),
                ('mon', models.BooleanField(default=True)),
                ('tue', models.BooleanField(default=True)),
                ('wed', models.BooleanField(default=True)),
                ('thu', models.BooleanField(default=True)),
                ('fri', models.BooleanField(default=True)),
                ('sat', models.BooleanField(default=True)),
                ('sun', models.BooleanField(default=True)),
                ('bookable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='rental.bookable')),
            ],
            options={
                'verbose_name': 'Availability',
                'verbose_name_plural': 'Availabilities',
                'ordering': ['bookable_id', 'start'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No-show')], db_index=True, default='REQUESTED', max_length=10)),
                ('price_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mode', models.CharField(blank=True, help_text='Snapshot of bookable.booking_mode', max_length=8)),
                ('unit', models.CharField(blank=True, help_text='Snapshot of the rent pricing unit', max_length=16)),
                ('msg', models.CharField(blank=True, max_length=255)),
                ('bookable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rental.bookable')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_bookings', to='identity.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals_created', to='identity.profile')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals_as_renter', to='identity.profile')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bookable', 'status', 'start'], name='rental_book_bookabl_9327fa_idx'), models.Index(fields=['renter', '-created_at'], name='rental_book_renter__e05317_idx')],
                'constraints': [django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['REQUESTED', 'CONFIRMED'])), expressions=[('bookable', '='), (rental.models.TsTzRange('start', 'end', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&')], name='rental_no_double_booking')],
            },
        ),
    ]
