# Generated by Django 5.2.15 on 2026-06-21 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_contract_kind'),
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancel_note',
            field=models.CharField(blank=True, help_text='Optional reason left at cancellation', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='Who cancelled the booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals_cancelled', to='identity.profile'),
        ),
    ]
