# Generated by Django 5.2.15 on 2026-06-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_booking_cancel_note_booking_cancelled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='recurrence_group',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ULID shared by occurrences of a recurring booking series (blank = standalone)', max_length=26),
        ),
    ]
