# Generated by Django 5.2.15 on 2026-06-24 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_remove_verification_notes'),
        ('rental', '0003_booking_recurrence_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='external_renter_name',
            field=models.CharField(blank=True, help_text='Walk-in / phone-in client name (set when renter is not a platform user)', max_length=120),
        ),
        migrations.AddField(
            model_name='booking',
            name='external_renter_phone',
            field=models.CharField(blank=True, help_text='Walk-in client contact phone (optional)', max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rentals_as_renter', to='identity.profile'),
        ),
    ]
