# Generated by Django 5.2.15 on 2026-06-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_booking_external_renter_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookable',
            name='requires_contract',
            field=models.CharField(choices=[('NEVER', 'Never'), ('THRESHOLD', 'When asset warrants it'), ('ALWAYS', 'Always')], default='THRESHOLD', help_text='When a CONFIRMED booking should spawn a rental Contract (see PK/rental-booking-system.md § Contract bridge)', max_length=10),
        ),
    ]
