# Generated by Django 5.2.15 on 2026-07-04 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('rental', '0005_alter_bookable_requires_contract'),
    ]

    operations = [
        # State-only: contracts.Contract keeps the identity_contract db_table,
        # so the FK column and constraint are unchanged at the database level.
        migrations.SeparateDatabaseAndState(database_operations=[], state_operations=[
        migrations.AlterField(
            model_name='booking',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_bookings', to='contracts.contract'),
        ),
        ]),
    ]
