# Generated by Django 5.2.12 on 2026-03-30 10:09

import core.models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import parasos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0002_initial'),
        ('identity', '0001_initial'),
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyGroup',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public (discoverable in Nearby)'), ('PRIVATE', 'Private (invite-only)')], default='PUBLIC', max_length=10)),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('radius_m', models.PositiveIntegerField(blank=True, default=1000, help_text='Coverage radius in meters', null=True)),
                ('matrix_room_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('quiet_hours_start', models.PositiveSmallIntegerField(blank=True, help_text='Hour (0-23) when INFO alerts are suppressed', null=True)),
                ('quiet_hours_end', models.PositiveSmallIntegerField(blank=True, help_text='Hour (0-23) when INFO suppression ends', null=True)),
                ('max_members', models.PositiveIntegerField(default=50, help_text='Maximum group members (0 = unlimited)')),
                ('members_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_safety_groups', to='identity.profile')),
                ('world_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_groups', to='geo.worldobject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InactivityWatch',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('max_inactivity_hours', models.PositiveIntegerField(default=12, help_text='Hours without activity before triggering alert')),
                ('check_start_hour', models.PositiveSmallIntegerField(default=8, help_text="Don't check before this hour (0-23)")),
                ('check_end_hour', models.PositiveSmallIntegerField(default=22, help_text="Don't check after this hour (0-23)")),
                ('last_activity_at', models.DateTimeField(blank=True, help_text='Last detected activity timestamp (updated by IoT/HA events)', null=True)),
                ('last_alert_at', models.DateTimeField(blank=True, help_text='When last inactivity alert was sent (avoid spam)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Pause monitoring (e.g. person is traveling)')),
                ('ha_home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inactivity_watches', to='iot.hahome')),
                ('iot_devices', models.ManyToManyField(blank=True, help_text='Sensors that count as activity (motion, door, fridge)', related_name='inactivity_watches', to='iot.iotdevice')),
                ('watched_profile', models.ForeignKey(help_text='Person being monitored', on_delete=django.db.models.deletion.CASCADE, related_name='inactivity_watches', to='identity.profile')),
                ('watchers', models.ManyToManyField(blank=True, help_text='Profiles notified on inactivity (family members)', related_name='watching_inactivity', to='identity.profile')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inactivity_watches', to='parasos.safetygroup')),
            ],
        ),
        migrations.CreateModel(
            name='GroupInvite',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('token', models.CharField(db_index=True, default=parasos.models._generate_invite_token, max_length=32, unique=True)),
                ('label', models.CharField(blank=True, help_text="Optional label (e.g. 'for family')", max_length=100)),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_group_invites', to='identity.profile')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='parasos.safetygroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyGroupMember',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('ADMIN', 'Admin')], default='MEMBER', max_length=10)),
                ('presence', models.CharField(choices=[('LOCAL', 'Local (can physically respond)'), ('REMOTE', 'Remote (coordinates remotely)')], default='LOCAL', max_length=10)),
                ('notify_info', models.BooleanField(default=False)),
                ('notify_warning', models.BooleanField(default=True)),
                ('notify_emergency', models.BooleanField(default=True)),
                ('quiet_hours_override', models.BooleanField(default=False, help_text='Ignore group quiet hours for this member')),
                ('emergency_context', models.TextField(blank=True, help_text='Medical info, allergies, doctor contacts — shown only during active SOS')),
                ('joined_matrix_room', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='parasos.safetygroup')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_memberships', to='identity.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('level', models.CharField(choices=[('INFO', 'Info (suspicious activity)'), ('WARNING', 'Warning (alarm triggered)'), ('EMERGENCY', 'Emergency (need help NOW)')], max_length=15)),
                ('category', models.CharField(choices=[('SUSPICIOUS_ACTIVITY', 'Suspicious activity'), ('ALARM_TRIGGERED', 'Alarm triggered'), ('MEDICAL', 'Medical emergency'), ('FIRE', 'Fire'), ('INTRUSION', 'Intrusion / break-in'), ('OTHER', 'Other')], default='OTHER', max_length=25)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual (SOS button)'), ('IOT_SENSOR', 'IoT sensor'), ('HA_AUTOMATION', 'Home Assistant automation')], default='MANUAL', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional text message')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text="Sender's location at time of SOS", null=True, srid=4326)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved'), ('FALSE_ALARM', 'False alarm')], default='ACTIVE', max_length=15)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('seen_count', models.PositiveIntegerField(default=0)),
                ('responding_count', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='parasos.safetygroup')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_sos_alerts', to='identity.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_sos_alerts', to='identity.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SOSResponse',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('status', models.CharField(choices=[('SEEN', 'Seen'), ('ON_WAY', 'On the way'), ('ON_SITE', 'On site'), ('UNABLE', 'Unable to respond')], default='SEEN', max_length=10)),
                ('note', models.TextField(blank=True, help_text='What responder sees / situation report')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='parasos.sosalert')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_responses', to='identity.profile')),
            ],
        ),
        migrations.AddIndex(
            model_name='safetygroup',
            index=models.Index(fields=['is_active', '-created_at'], name='parasos_saf_is_acti_180dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='safetygroup',
            index=models.Index(fields=['created_by'], name='parasos_saf_created_024159_idx'),
        ),
        migrations.AddIndex(
            model_name='inactivitywatch',
            index=models.Index(fields=['is_active', 'last_activity_at'], name='parasos_ina_is_acti_298f1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inactivitywatch',
            unique_together={('group', 'watched_profile')},
        ),
        migrations.AddIndex(
            model_name='groupinvite',
            index=models.Index(fields=['group', 'is_active'], name='parasos_gro_group_i_27cbbb_idx'),
        ),
        migrations.AddIndex(
            model_name='safetygroupmember',
            index=models.Index(fields=['group', 'role'], name='parasos_saf_group_i_47890f_idx'),
        ),
        migrations.AddIndex(
            model_name='safetygroupmember',
            index=models.Index(fields=['profile'], name='parasos_saf_profile_75dc31_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='safetygroupmember',
            unique_together={('group', 'profile')},
        ),
        migrations.AddIndex(
            model_name='sosalert',
            index=models.Index(fields=['group', 'status', '-created_at'], name='parasos_sos_group_i_7e6094_idx'),
        ),
        migrations.AddIndex(
            model_name='sosalert',
            index=models.Index(fields=['sender', '-created_at'], name='parasos_sos_sender__5d1065_idx'),
        ),
        migrations.AddIndex(
            model_name='sosalert',
            index=models.Index(fields=['status', '-created_at'], name='parasos_sos_status_c6b72b_idx'),
        ),
        migrations.AddIndex(
            model_name='sosresponse',
            index=models.Index(fields=['alert', 'status'], name='parasos_sos_alert_i_45b177_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sosresponse',
            unique_together={('alert', 'responder')},
        ),
    ]
