# Generated by Django 5.2.12 on 2026-03-30 10:09

import core.models
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text='Default name (fallback)', max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('name_i18n', models.JSONField(blank=True, default=dict, help_text='Translated names by language code')),
                ('description_i18n', models.JSONField(blank=True, default=dict, help_text='Translated descriptions by language code')),
                ('icon', models.CharField(blank=True, help_text='Emoji icon for UI', max_length=10)),
                ('image', models.CharField(blank=True, help_text='Image URL', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Is category active')),
                ('item_count', models.IntegerField(default=0, help_text='Number of items in category')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('sale_only', models.BooleanField(default=False, help_text='Items in this category can only be sold, not rented (e.g., food, hygiene products)')),
                ('applicable_to', models.JSONField(blank=True, default=list, help_text='Subsystems: ["market"], ["directory"], ["market","directory"], ["events"]')),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='taxonomy.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['attributes'], name='taxonomy_ta_attribu_55fec1_gin'), django.contrib.postgres.indexes.GinIndex(fields=['relations'], name='taxonomy_ta_relatio_8c14e6_gin')],
            },
        ),
    ]
