# Generated by Django 5.2.12 on 2026-03-30 10:09

import core.models
import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('name', models.CharField(max_length=200)),
                ('post_title', models.CharField(max_length=200)),
                ('post_content', models.TextField()),
                ('link', models.URLField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/%Y/%m/%d/')),
                ('budget_sats', models.BigIntegerField()),
                ('spent_sats', models.BigIntegerField(default=0)),
                ('reward_sats', models.IntegerField(help_text='Satoshis paid per view')),
                ('target_gender', models.CharField(choices=[('any', 'Any'), ('male', 'Male'), ('female', 'Female')], default='any', max_length=10)),
                ('target_age_from', models.IntegerField(default=18)),
                ('target_age_to', models.IntegerField(default=65)),
                ('target_min_skill_level', models.IntegerField(default=1, help_text='1-5, viewer must have at least one skill at this level or higher')),
                ('target_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('target_radius_km', models.FloatField(default=0, help_text='0 = no geo filter')),
                ('include_self', models.BooleanField(default=False, help_text='If True, always show to advertiser regardless of targeting (monitoring)')),
                ('exclude_self', models.BooleanField(default=False, help_text='If True, never show to advertiser even if matching targeting')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], db_index=True, default='draft', max_length=20)),
                ('total_views', models.IntegerField(default=0)),
                ('total_clicks', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ads_adcampaign',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdsChildrenAge',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ads_children_age',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdsInterest',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ads_interest',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdsProfile',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('gender', models.CharField(choices=[('any', 'Any'), ('male', 'Male'), ('female', 'Female')], default='any', max_length=10)),
                ('birth_date', models.DateField(blank=True, help_text='Date of birth for age-based targeting', null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('min_reward_sats', models.IntegerField(default=10, help_text="Minimum satoshis per ad view (user won't see ads below this)")),
                ('ln_wallet_config', models.JSONField(blank=True, default=dict, help_text='Encrypted wallet credentials (admin keys for paying, invoice keys for receiving)')),
                ('total_views', models.IntegerField(default=0)),
                ('total_earned_sats', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'ads_profile',
            },
        ),
        migrations.CreateModel(
            name='AdsProfileLocation',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('label', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
            options={
                'db_table': 'ads_profile_location',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdsProfileSkill',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('level', models.IntegerField(default=1, help_text='Skill level 1-5 (Beginner/Intermediate/Advanced/Expert/Master)')),
            ],
            options={
                'db_table': 'ads_profile_skill',
            },
        ),
        migrations.CreateModel(
            name='AdsSkill',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ads_skill',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdView',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('viewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('clicked', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('payment_sent', models.BooleanField(default=False)),
                ('payment_amount_sats', models.IntegerField(default=0)),
                ('payment_invoice', models.CharField(blank=True, help_text='Lightning invoice used for payment', max_length=2000)),
                ('payment_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ads_adview',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
