# Generated by Django 5.2.12 on 2026-03-30 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        ('finance', '0001_initial'),
        ('geo', '0001_initial'),
        ('identity', '0001_initial'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaign',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='establishment',
            field=models.ForeignKey(blank=True, help_text='If set, campaign is posted on behalf of this establishment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_campaigns', to='geo.establishment'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='linked_establishment',
            field=models.ForeignKey(blank=True, help_text='Linked establishment to promote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_campaigns', to='geo.establishment'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='linked_item',
            field=models.ForeignKey(blank=True, help_text='Linked marketplace item to promote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_campaigns', to='market.item'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='target_children_ages',
            field=models.ManyToManyField(blank=True, related_name='targeted_campaigns', to='ads.adschildrenage'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='target_interests',
            field=models.ManyToManyField(blank=True, help_text='Target users with these interests (empty = any interest)', related_name='campaigns', to='ads.adsinterest'),
        ),
        migrations.AddField(
            model_name='adsprofile',
            name='children_ages',
            field=models.ManyToManyField(blank=True, help_text="Ages of user's children for family-targeted ads", related_name='users', to='ads.adschildrenage'),
        ),
        migrations.AddField(
            model_name='adsprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, help_text="User's interests for targeted advertising", related_name='users', to='ads.adsinterest'),
        ),
        migrations.AddField(
            model_name='adsprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ads_profile', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='adsprofilelocation',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='ads.adsprofile'),
        ),
        migrations.AddField(
            model_name='adsprofileskill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_ratings', to='ads.adsprofile'),
        ),
        migrations.AddField(
            model_name='adsprofileskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.adsskill'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='target_skills',
            field=models.ManyToManyField(blank=True, related_name='targeted_campaigns', to='ads.adsskill'),
        ),
        migrations.AddField(
            model_name='adview',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='ads.adcampaign'),
        ),
        migrations.AddField(
            model_name='adview',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ad_view', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='adview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_views', to='identity.profile'),
        ),
        migrations.AddIndex(
            model_name='adsprofile',
            index=models.Index(fields=['gender', 'age'], name='ads_profile_gender_2e4d7d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adsprofileskill',
            unique_together={('profile', 'skill')},
        ),
        migrations.AddIndex(
            model_name='adcampaign',
            index=models.Index(fields=['status', '-created_at'], name='ads_adcampa_status_7cf6bf_idx'),
        ),
        migrations.AddIndex(
            model_name='adcampaign',
            index=models.Index(fields=['advertiser', 'status'], name='ads_adcampa_adverti_d7f2e9_idx'),
        ),
        migrations.AddIndex(
            model_name='adview',
            index=models.Index(fields=['campaign', '-viewed_at'], name='ads_adview_campaig_3776c8_idx'),
        ),
        migrations.AddIndex(
            model_name='adview',
            index=models.Index(fields=['user', '-viewed_at'], name='ads_adview_user_id_df77bc_idx'),
        ),
        migrations.AddIndex(
            model_name='adview',
            index=models.Index(fields=['payment_sent'], name='ads_adview_payment_6a5296_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adview',
            unique_together={('user', 'campaign')},
        ),
    ]
