# Generated by Django 5.2.12 on 2026-03-30 10:09

import core.models
import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('identity', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, default='', help_text='URL-friendly identifier, auto-generated from title', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('CREDIT', 'Offer'), ('DEBIT', 'Request')], db_index=True, max_length=10)),
                ('spec_data', models.JSONField(blank=True, default=dict)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('pricing_options', models.JSONField(blank=True, default=list, help_text="Array of pricing options. Each option: {type: 'sale'|'rent'|'free', amount: number, currency: 'EUR'|'USD'|..., unit?: 'kg'|'hour'|'day'|'pcs'|..., note?: string}. Examples: [{type: 'sale', amount: 2, currency: 'EUR', unit: 'kg'}, {type: 'rent', amount: 800, currency: 'EUR', unit: 'month'}]")),
                ('accepted_payment_methods', models.JSONField(blank=True, default=list, help_text='Array of accepted payment method codes')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('language', models.CharField(blank=True, db_index=True, default='', help_text='Content language (ISO 639-1: en/ru/pt/es/fr/de). Empty = unspecified (shown to all).', max_length=5)),
                ('is_international', models.BooleanField(db_index=True, default=False, help_text='Visible to all users regardless of language filter (e.g. remote services, souvenirs)')),
                ('country_code', models.CharField(blank=True, db_index=True, default='', help_text='ISO 3166-1 alpha-2 country code from item coordinates. Empty = no location/digital.', max_length=2)),
                ('version', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='taxonomy.category')),
                ('establishment', models.ForeignKey(blank=True, help_text='If set, item is posted on behalf of this establishment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_items', to='geo.establishment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='identity.profile')),
                ('tags', models.ManyToManyField(blank=True, related_name='items', to='taxonomy.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('peertube_uuid', models.CharField(blank=True, db_index=True, max_length=36)),
                ('peertube_url', models.URLField(blank=True, max_length=512)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=512)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('magnet_link', models.TextField(blank=True)),
                ('ipfs_cid', models.CharField(blank=True, db_index=True, max_length=255)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_metadata', to='market.item')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_active', 'type', '-created_at'], name='market_item_is_acti_621ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['owner', 'is_active', '-created_at'], name='market_item_owner_i_7b902a_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_active', 'language', 'country_code'], name='market_item_is_acti_3f6831_idx'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('slug', ''), _negated=True), fields=('slug',), name='unique_item_slug'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=django.contrib.postgres.indexes.GinIndex(fields=['attributes'], name='market_vide_attribu_0bff05_gin'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=django.contrib.postgres.indexes.GinIndex(fields=['relations'], name='market_vide_relatio_720578_gin'),
        ),
    ]
