# Generated by Django 5.2.12 on 2026-03-31 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
