# Generated by Django 5.2.15 on 2026-06-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_delete_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='self_made',
            field=models.BooleanField(db_index=True, default=False, help_text="Seller is the producer — made / grew / prepared it themselves — not a reseller. Drives the 'made by hand' badge and a ranking nudge (swadeshi / bread-labour: prefer own-and-near). Bought parts/ingredients don't disqualify; reselling finished goods does. Offers (CREDIT) only."),
        ),
    ]
