# Generated by Django 5.2.15 on 2026-06-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_item_self_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public — anyone, incl. anonymous & search engines'), ('REGISTERED', 'Registered — signed-in parahub users only')], db_index=True, default='PUBLIC', help_text='Audience scope. PUBLIC = discoverable by anyone incl. anonymous visitors and search engines (default). REGISTERED = hidden from anonymous + SEO, visible only to signed-in parahub users. Orthogonal to is_active (which is the draft/paused switch).', max_length=12),
        ),
    ]
