"""
Export categories to separate JSON files per language for frontend static loading.

Creates content-addressed files: categories.{lang}.{hash}.json
Generates manifest: frontend/data/categories-versions.js

Usage:
    python manage.py export_categories_json [--output-dir frontend/public/data]
"""

import json
import os
import hashlib
from django.core.management.base import BaseCommand
from taxonomy.models import Category
from taxonomy.schemas import CategoryTreeSchema


def build_category_tree(category, lang='en'):
    """Build a CategoryTreeSchema tree node recursively for a given language."""
    name = category.get_name(lang)
    children_qs = category.children.filter(is_active=True).order_by('order', 'name')
    children = [build_category_tree(child, lang) for child in children_qs]
    return CategoryTreeSchema(
        id=category.id,
        name=name,
        slug=category.slug,
        icon=category.icon or '',
        applicable_to=category.applicable_to or [],
        children=children,
    )


class Command(BaseCommand):
    help = 'Export categories to content-addressed JSON files per language'

    # Supported languages
    LANGUAGES = ['en', 'ru', 'pt', 'es', 'fr', 'de']

    def add_arguments(self, parser):
        parser.add_argument(
            '--output-dir',
            type=str,
            default='frontend/public/data',
            help='Output directory for JSON files'
        )

    def handle(self, *args, **options):
        output_dir = options['output_dir']
        manifest_dir = 'frontend/data'

        # Create output directories if they don't exist
        os.makedirs(output_dir, exist_ok=True)
        os.makedirs(manifest_dir, exist_ok=True)

        self.stdout.write(self.style.SUCCESS(f"\n📁 Exporting categories to: {output_dir}\n"))

        # Get root categories
        root_categories = Category.objects.filter(parent__isnull=True).order_by('order', 'name')
        total_categories = Category.objects.count()

        self.stdout.write(f"Found {total_categories} categories ({len(root_categories)} root)\n")

        # Store versions for manifest
        versions = {}

        # Export for each language
        for lang in self.LANGUAGES:
            self.stdout.write(f"Exporting {lang.upper()}... ", ending='')

            # Build tree for this language
            tree = [build_category_tree(cat, lang) for cat in root_categories]

            # Convert to dict for JSON serialization
            tree_dict = [self._serialize_tree_node(node) for node in tree]

            # Serialize to JSON string
            json_content = json.dumps(tree_dict, ensure_ascii=False, indent=2)

            # Calculate content hash (first 8 chars of SHA256)
            content_hash = hashlib.sha256(json_content.encode('utf-8')).hexdigest()[:8]
            versions[lang] = content_hash

            # Generate filename with hash
            output_file = os.path.join(output_dir, f'categories.{lang}.{content_hash}.json')

            # Only write if file doesn't exist (same hash = same content)
            if os.path.exists(output_file):
                file_size = os.path.getsize(output_file)
                size_kb = file_size / 1024
                self.stdout.write(self.style.WARNING(f"⊙ {size_kb:.1f} KB (unchanged)"))
            else:
                # Write to file
                with open(output_file, 'w', encoding='utf-8') as f:
                    f.write(json_content)

                # Calculate file size
                file_size = os.path.getsize(output_file)
                size_kb = file_size / 1024

                self.stdout.write(self.style.SUCCESS(f"✓ {size_kb:.1f} KB (new)"))

                # Clean up old versions for this language
                self._cleanup_old_versions(output_dir, lang, content_hash)

        # Generate manifest file
        manifest_file = os.path.join(manifest_dir, 'categories-versions.js')
        self.stdout.write(f"\nGenerating manifest: {manifest_file}... ", ending='')

        manifest_content = f"""// Auto-generated by export_categories_json management command
// DO NOT EDIT MANUALLY

export const CATEGORY_VERSIONS = {{
{self._format_versions_dict(versions)}
}}
"""

        with open(manifest_file, 'w', encoding='utf-8') as f:
            f.write(manifest_content)

        self.stdout.write(self.style.SUCCESS("✓"))

        self.stdout.write(self.style.SUCCESS(
            f"\n✅ Export complete!\n"
            f"  JSON files: {len(self.LANGUAGES)} languages\n"
            f"  Manifest: {manifest_file}\n"
        ))

    def _serialize_tree_node(self, node):
        """Convert CategoryTreeSchema to dict recursively"""
        return {
            'id': node.id,
            'name': node.name,
            'slug': node.slug,
            'icon': node.icon,
            'applicable_to': node.applicable_to,
            'children': [self._serialize_tree_node(child) for child in node.children] if node.children else []
        }

    def _format_versions_dict(self, versions):
        """Format versions dictionary for JavaScript"""
        lines = []
        for lang, hash_val in sorted(versions.items()):
            lines.append(f"  {lang}: '{hash_val}'")
        return ',\n'.join(lines)

    def _cleanup_old_versions(self, output_dir, lang, current_hash):
        """Remove old versioned files for a language, keeping only the current one"""
        import glob

        # Find all files matching categories.{lang}.*.json
        pattern = os.path.join(output_dir, f'categories.{lang}.*.json')
        old_files = glob.glob(pattern)

        current_file = os.path.join(output_dir, f'categories.{lang}.{current_hash}.json')

        for old_file in old_files:
            if old_file != current_file:
                try:
                    os.remove(old_file)
                    self.stdout.write(f"\n  Removed old version: {os.path.basename(old_file)}")
                except OSError as e:
                    self.stdout.write(self.style.WARNING(f"\n  Failed to remove {old_file}: {e}"))
