# Generated by Django 5.2.12 on 2026-03-30 10:09

import core.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('warning_hours', models.IntegerField(default=24)),
                ('poll_type', models.CharField(choices=[('simple', 'Yes/No'), ('multiple_choice', 'Multiple Choice'), ('ranked', 'Ranked Choice'), ('quadratic', 'Quadratic')], default='multiple_choice', max_length=20)),
                ('quorum_type', models.CharField(choices=[('simple_majority', '50%+1'), ('qualified_majority', '2/3'), ('unanimous', '100%'), ('custom', 'Custom %')], default='simple_majority', max_length=20)),
                ('quorum_percent', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('use_weights', models.BooleanField(default=False)),
                ('weight_source', models.CharField(blank=True, choices=[('wot_reputation', 'WoT Reputation'), ('ownership_shares', 'Доля собственности'), ('custom', 'Custom weights')], max_length=20, null=True)),
                ('allow_delegation', models.BooleanField(default=True)),
                ('require_wot_verified', models.BooleanField(default=False)),
                ('public_results', models.BooleanField(default=True)),
                ('merkle_root', models.CharField(blank=True, max_length=64, null=True)),
                ('result_pgp_signature', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'governance_poll',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollAuditLog',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('action', models.CharField(choices=[('poll_created', 'Poll Created'), ('poll_started', 'Poll Started'), ('vote_cast', 'Vote Cast'), ('delegation_created', 'Delegation Created'), ('delegation_revoked', 'Delegation Revoked'), ('poll_ended', 'Poll Ended')], max_length=30)),
                ('previous_log_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('current_log_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('pgp_signature', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'governance_poll_audit_log',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PollContext',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('context_type', models.CharField(choices=[('organization', 'Organization'), ('community', 'Community'), ('tszh', 'ТСЖ/HOA'), ('adhoc', 'Ad-hoc группа')], max_length=20)),
                ('context_id', models.CharField(max_length=26)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'governance_poll_context',
            },
        ),
        migrations.CreateModel(
            name='PollEligibleVoter',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('weight', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
            ],
            options={
                'db_table': 'governance_poll_eligible_voter',
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('text', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'governance_poll_option',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('pgp_signature', models.TextField()),
                ('signed_payload', models.JSONField()),
                ('voted_on_behalf_of', models.JSONField(default=list)),
                ('effective_weight', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'governance_poll_vote',
            },
        ),
        migrations.CreateModel(
            name='PollVoteDelegation',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('pgp_signature', models.TextField()),
                ('signed_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_signature', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'governance_poll_vote_delegation',
            },
        ),
    ]
