# Generated by Django 5.2.12 on 2026-03-30 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('governance', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls_created', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='pollauditlog',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_audit_actions', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='pollauditlog',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='governance.poll'),
        ),
        migrations.AddField(
            model_name='pollcontext',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_contexts_created', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='poll',
            name='context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='governance.pollcontext'),
        ),
        migrations.AddField(
            model_name='polleligiblevoter',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_voters', to='governance.poll'),
        ),
        migrations.AddField(
            model_name='polleligiblevoter',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_polls', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='polloption',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='governance.poll'),
        ),
        migrations.AddField(
            model_name='pollvote',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='governance.polloption'),
        ),
        migrations.AddField(
            model_name='pollvote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_votes', to='governance.poll'),
        ),
        migrations.AddField(
            model_name='pollvote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes_cast', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='pollvotedelegation',
            name='delegate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_delegations_received', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='pollvotedelegation',
            name='delegator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_delegations_given', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='pollvotedelegation',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_delegations', to='governance.poll'),
        ),
        migrations.AddIndex(
            model_name='pollauditlog',
            index=models.Index(fields=['poll', 'timestamp'], name='governance__poll_id_965d1a_idx'),
        ),
        migrations.AddIndex(
            model_name='pollcontext',
            index=models.Index(fields=['context_type', 'context_id'], name='governance__context_e62930_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['status', '-created_at'], name='governance__status_a5f40a_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['context', 'status'], name='governance__context_218c32_idx'),
        ),
        migrations.AddIndex(
            model_name='polleligiblevoter',
            index=models.Index(fields=['poll', 'profile'], name='governance__poll_id_3884fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='polleligiblevoter',
            unique_together={('poll', 'profile')},
        ),
        migrations.AlterUniqueTogether(
            name='polloption',
            unique_together={('poll', 'order')},
        ),
        migrations.AddIndex(
            model_name='pollvote',
            index=models.Index(fields=['poll', 'created_at'], name='governance__poll_id_66323c_idx'),
        ),
        migrations.AddIndex(
            model_name='pollvote',
            index=models.Index(fields=['poll', 'option'], name='governance__poll_id_1455b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pollvote',
            unique_together={('poll', 'voter')},
        ),
        migrations.AddIndex(
            model_name='pollvotedelegation',
            index=models.Index(fields=['poll', 'is_active'], name='governance__poll_id_5ad211_idx'),
        ),
        migrations.AddIndex(
            model_name='pollvotedelegation',
            index=models.Index(fields=['poll', 'delegate', 'is_active'], name='governance__poll_id_33a509_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pollvotedelegation',
            unique_together={('poll', 'delegator')},
        ),
    ]
