# Generated by Django 5.2.15 on 2026-07-02 17:43

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_initial'),
        ('identity', '0008_profile_civic_opinion_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='ballot_mode',
            field=models.CharField(choices=[('open', 'Open'), ('anonymous', 'Anonymous')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='poll',
            name='civic_destination',
            field=models.CharField(blank=True, default='', help_text="Where the result goes (e.g. 'Junta de Freguesia de Moncao, 2026-09-01') — efficacy commitment", max_length=300),
        ),
        migrations.AddField(
            model_name='poll',
            name='civic_outcome',
            field=models.TextField(blank=True, default='', help_text='What actually happened after the poll — closes the loop'),
        ),
        migrations.AddField(
            model_name='poll',
            name='frozen_results',
            field=models.JSONField(blank=True, help_text='Aggregates frozen at purge time (30d after end) when raw opinion votes are deleted', null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_class',
            field=models.CharField(choices=[('decision', 'Decision'), ('opinion', 'Opinion')], db_index=True, default='decision', max_length=10),
        ),
        migrations.AddField(
            model_name='pollauditlog',
            name='actor_ulid',
            field=models.CharField(blank=True, default='', max_length=26),
        ),
        migrations.AlterField(
            model_name='pollauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_audit_actions', to='identity.profile'),
        ),
        migrations.AlterField(
            model_name='pollcontext',
            name='context_type',
            field=models.CharField(choices=[('organization', 'Organization'), ('community', 'Community'), ('tszh', 'ТСЖ/HOA'), ('adhoc', 'Ad-hoc группа'), ('territory', 'Territory'), ('household', 'Household'), ('condominium', 'Condominium')], max_length=20),
        ),
        migrations.CreateModel(
            name='OpinionVote',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('voter_token', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('voter_territory', models.CharField(blank=True, default='', help_text="Municipality-level code (DICO) for k>=5 breakdowns; parish polls carry the poll's own code", max_length=16)),
                ('voter_wot_verified', models.BooleanField(default=False)),
                ('via_delegation', models.BooleanField(default=False)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinion_votes', to='governance.poll')),
            ],
            options={
                'db_table': 'governance_opinion_vote',
                'indexes': [models.Index(fields=['poll', 'created_at'], name='governance__poll_id_474d59_idx'), models.Index(fields=['poll', 'voter_territory'], name='governance__poll_id_40e554_idx')],
                'unique_together': {('poll', 'voter_token')},
            },
        ),
    ]
