# Generated by Django 5.2.15 on 2026-07-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0004_backfill_actor_ulid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollauditlog',
            name='action',
            field=models.CharField(choices=[('poll_created', 'Poll Created'), ('poll_started', 'Poll Started'), ('vote_cast', 'Vote Cast'), ('delegation_created', 'Delegation Created'), ('delegation_revoked', 'Delegation Revoked'), ('poll_ended', 'Poll Ended'), ('opinion_vote', 'Opinion Vote (pseudonymous)'), ('opinion_erased', 'Opinion Votes Erased (GDPR)')], max_length=30),
        ),
    ]
