# Generated by Django 5.2.15 on 2026-07-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0005_alter_pollauditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_type',
            field=models.CharField(choices=[('simple', 'Yes/No'), ('multiple_choice', 'Multiple Choice'), ('ranked', 'Ranked Choice'), ('quadratic', 'Quadratic'), ('sliders', 'Sliders')], default='multiple_choice', max_length=20),
        ),
    ]
