# Generated by Django 5.2.15 on 2026-07-02 19:02

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0037_territory'),
        ('governance', '0006_alter_poll_poll_type'),
        ('identity', '0008_profile_civic_opinion_consent_and_more'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Civic topic (curated subset) — standing topic delegations match on this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='civic_polls', to='taxonomy.category'),
        ),
        migrations.CreateModel(
            name='StandingDelegation',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('scope_type', models.CharField(choices=[('topic', 'Topic'), ('territory', 'Territory')], max_length=10)),
                ('pgp_signature', models.TextField(blank=True, default='')),
                ('signed_payload', models.JSONField(blank=True, default=dict)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standing_delegations_received', to='identity.profile')),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standing_delegations_given', to='identity.profile')),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standing_delegations', to='geo.territory')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standing_delegations', to='taxonomy.category')),
            ],
            options={
                'db_table': 'governance_standing_delegation',
                'indexes': [models.Index(fields=['delegate', 'is_active'], name='governance__delegat_e53bda_idx'), models.Index(fields=['delegator', 'is_active'], name='governance__delegat_efad77_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('delegator', 'scope_type', 'topic', 'territory'), name='unique_active_standing_delegation_per_scope')],
            },
        ),
    ]
