# Generated by Django 5.2.15 on 2026-07-02 19:27

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0037_territory'),
        ('governance', '0007_poll_topic_standingdelegation'),
        ('identity', '0008_profile_civic_opinion_consent_and_more'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CivicIdea',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=4000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('review', 'Review (threshold reached)'), ('promoted', 'Promoted to poll'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='open', max_length=10)),
                ('support_count', models.IntegerField(default=0)),
                ('reports_count', models.IntegerField(default=0)),
                ('review_note', models.CharField(blank=True, default='', max_length=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civic_ideas', to='identity.profile')),
                ('promoted_poll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_ideas', to='governance.poll')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='civic_ideas_reviewed', to='identity.profile')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civic_ideas', to='geo.territory')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='civic_ideas', to='taxonomy.category')),
            ],
            options={
                'db_table': 'governance_civic_idea',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CivicIdeaSupport',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='governance.civicidea')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civic_idea_supports', to='identity.profile')),
            ],
            options={
                'db_table': 'governance_civic_idea_support',
            },
        ),
        migrations.AddIndex(
            model_name='civicidea',
            index=models.Index(fields=['territory', 'status', '-created_at'], name='governance__territo_4e839a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='civicideasupport',
            unique_together={('idea', 'profile')},
        ),
    ]
