# Generated by Django 5.2.12 on 2026-03-30 10:09

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('name', models.CharField(help_text='English name (reference data pattern)', max_length=120)),
                ('slug', models.SlugField(help_text='For i18n lookup: treasury.category.<slug>', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='lucide icon name', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by_poll_id', models.CharField(blank=True, help_text='Poll that created this category', max_length=26)),
                ('deactivated_by_poll_id', models.CharField(blank=True, help_text='Poll that deactivated this', max_length=26)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('establishment', models.ForeignKey(help_text='Establishment this category belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories', to='geo.establishment')),
            ],
            options={
                'verbose_name_plural': 'Budget categories',
                'db_table': 'treasury_budget_category',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetEpoch',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('label', models.CharField(help_text='e.g. 2026-03', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('finalized', 'Finalized')], db_index=True, default='active', max_length=20)),
                ('frozen_allocations', models.JSONField(default=list, help_text='[{category_id, slug, name, median_percent, voter_count}]')),
                ('total_eligible', models.IntegerField(default=0)),
                ('total_participants', models.IntegerField(default=0)),
                ('merkle_root', models.CharField(blank=True, max_length=64)),
                ('individual_allocations_snapshot', models.JSONField(default=list, help_text='[{profile_id, hna, allocations, pgp_signature}]')),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('establishment', models.ForeignKey(help_text='Establishment this epoch belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='budget_epochs', to='geo.establishment')),
            ],
            options={
                'db_table': 'treasury_budget_epoch',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in EUR', max_digits=12)),
                ('description', models.TextField(help_text='What was this expense for')),
                ('receipt_url', models.URLField(blank=True, help_text='URL to receipt image/document')),
                ('date', models.DateField(help_text='Date of the expense')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10)),
                ('epoch_label', models.CharField(blank=True, help_text='Budget epoch label (YYYY-MM)', max_length=20)),
                ('category', models.ForeignKey(blank=True, help_text='Budget category this expense falls under', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='treasury.budgetcategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to='identity.profile')),
                ('establishment', models.ForeignKey(help_text='Establishment this expense belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='geo.establishment')),
            ],
            options={
                'db_table': 'treasury_expense',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryAuditLog',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('action', models.CharField(choices=[('allocation_updated', 'Allocation Updated'), ('epoch_finalized', 'Epoch Finalized'), ('category_created', 'Category Created'), ('category_deactivated', 'Category Deactivated'), ('expense_created', 'Expense Created'), ('expense_approved', 'Expense Approved')], max_length=30)),
                ('previous_log_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('current_log_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('pgp_signature', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, help_text='null for system actions (epoch freeze)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_audit_actions', to='identity.profile')),
                ('establishment', models.ForeignKey(help_text='Establishment this log belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='treasury_audit_logs', to='geo.establishment')),
            ],
            options={
                'db_table': 'treasury_audit_log',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('allocations', models.JSONField(default=dict, help_text='{"category_id": Decimal percentage}, sum = 100.0')),
                ('pgp_signature', models.TextField(blank=True)),
                ('signed_payload', models.JSONField(blank=True, default=dict)),
                ('establishment', models.ForeignKey(help_text='Establishment this allocation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='geo.establishment')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='identity.profile')),
            ],
            options={
                'db_table': 'treasury_budget_allocation',
                'constraints': [models.UniqueConstraint(fields=('profile', 'establishment'), name='unique_allocation_per_profile_establishment')],
            },
        ),
        migrations.AddConstraint(
            model_name='budgetcategory',
            constraint=models.UniqueConstraint(fields=('establishment', 'slug'), name='unique_category_per_establishment'),
        ),
        migrations.AddConstraint(
            model_name='budgetepoch',
            constraint=models.UniqueConstraint(fields=('establishment', 'label'), name='unique_epoch_per_establishment'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['establishment', 'date'], name='treasury_ex_establi_475916_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['establishment', 'status'], name='treasury_ex_establi_d3f778_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category', 'date'], name='treasury_ex_categor_5e5ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='treasuryauditlog',
            index=models.Index(fields=['action', 'timestamp'], name='treasury_au_action_77b340_idx'),
        ),
    ]
