# Generated by Django 5.2.12 on 2026-03-30 10:09

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('identity', '0001_initial'),
        ('market', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Profile that manages this agency via UI', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_agencies', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='calendardate',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_dates', to='geo.agency'),
        ),
        migrations.AddField(
            model_name='condominiumfraction',
            name='resident',
            field=models.ForeignKey(blank=True, help_text='Current resident (owner or tenant)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condo_fractions', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='drivershift',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_shifts', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Primary business category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establishments', to='taxonomy.category'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='items',
            field=models.ManyToManyField(blank=True, help_text='Items sold/offered at this establishment', related_name='establishments', to='market.item'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='owner',
            field=models.ForeignKey(help_text='Profile that created this establishment', on_delete=django.db.models.deletion.CASCADE, related_name='establishments', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent establishment for franchises/networks', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='geo.establishment'),
        ),
        migrations.AddField(
            model_name='condominiumfraction',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fractions', to='geo.establishment'),
        ),
        migrations.AddField(
            model_name='agency',
            name='establishment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transit_profile', to='geo.establishment'),
        ),
        migrations.AddField(
            model_name='establishmentmembership',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='geo.establishment'),
        ),
        migrations.AddField(
            model_name='establishmentmembership',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishment_memberships', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_of_establishments', through='geo.EstablishmentMembership', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='establishmentreview',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishment_reviews', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='establishmentreview',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='geo.establishment'),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Event category from taxonomy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='taxonomy.category'),
        ),
        migrations.AddField(
            model_name='event',
            name='establishment',
            field=models.ForeignKey(blank=True, help_text='If set, event is posted on behalf of this establishment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to='geo.establishment'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(help_text='Profile that created this event', on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participants', to='geo.event'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='openskymission',
            name='pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opensky_missions', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='openskytilelayer',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tile_layers', to='geo.openskymission'),
        ),
        migrations.AddField(
            model_name='place',
            name='parent_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_places', to='geo.place'),
        ),
        migrations.AddField(
            model_name='quotapayment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='quotapayment',
            name='fraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='geo.condominiumfraction'),
        ),
        migrations.AddField(
            model_name='route',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='geo.agency'),
        ),
        migrations.AddField(
            model_name='route',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='geo.place'),
        ),
        migrations.AddField(
            model_name='route',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='m2m_routes', to='geo.place'),
        ),
        migrations.AddField(
            model_name='drivershift',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_shifts', to='geo.route'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='geo.route'),
        ),
        migrations.AddField(
            model_name='stop',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='geo.agency'),
        ),
        migrations.AddField(
            model_name='stop',
            name='parent_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_stops', to='geo.stop'),
        ),
        migrations.AddField(
            model_name='stop',
            name='place',
            field=models.ForeignKey(blank=True, help_text='Cached: place this stop belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stops', to='geo.place'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='geo.stop'),
        ),
        migrations.AddField(
            model_name='stoptime',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='geo.stop'),
        ),
        migrations.AddIndex(
            model_name='transitdatasource',
            index=django.contrib.postgres.indexes.GinIndex(fields=['attributes'], name='geo_transit_attribu_b3d4d4_gin'),
        ),
        migrations.AddIndex(
            model_name='transitdatasource',
            index=django.contrib.postgres.indexes.GinIndex(fields=['relations'], name='geo_transit_relatio_d2f61d_gin'),
        ),
        migrations.AddField(
            model_name='drivershift',
            name='data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_shifts', to='geo.transitdatasource'),
        ),
        migrations.AddField(
            model_name='agency',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agencies', to='geo.transitdatasource'),
        ),
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='geo.route'),
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle_item',
            field=models.ForeignKey(blank=True, limit_choices_to={'spec_type': 'VEHICLE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.item'),
        ),
        migrations.AddField(
            model_name='stoptime',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='geo.trip'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='geo.agency'),
        ),
        migrations.AddField(
            model_name='vehiclepositionhistory',
            name='data_source',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='position_history', to='geo.transitdatasource'),
        ),
        migrations.AddField(
            model_name='worldobject',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_objects', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='event',
            name='world_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='geo.worldobject'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='world_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establishments', to='geo.worldobject'),
        ),
        migrations.AddIndex(
            model_name='calendardate',
            index=models.Index(fields=['agency', 'date', 'exception_type'], name='geo_calenda_agency__5219f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calendardate',
            unique_together={('agency', 'service_id', 'date')},
        ),
        migrations.AddIndex(
            model_name='condominiumfraction',
            index=models.Index(fields=['establishment', 'resident'], name='geo_condomi_establi_02d50e_idx'),
        ),
        migrations.AddIndex(
            model_name='condominiumfraction',
            index=models.Index(fields=['establishment', 'floor'], name='geo_condomi_establi_a50d37_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='condominiumfraction',
            unique_together={('establishment', 'identifier')},
        ),
        migrations.AddIndex(
            model_name='establishmentmembership',
            index=models.Index(fields=['establishment', 'role'], name='geo_establi_establi_bf7ce6_idx'),
        ),
        migrations.AddIndex(
            model_name='establishmentmembership',
            index=models.Index(fields=['profile', 'created_at'], name='geo_establi_profile_2786d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='establishmentmembership',
            unique_together={('profile', 'establishment')},
        ),
        migrations.AddIndex(
            model_name='establishmentreview',
            index=models.Index(fields=['establishment', '-created_at'], name='geo_establi_establi_6cc727_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='establishmentreview',
            unique_together={('establishment', 'author')},
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['event', 'status'], name='geo_eventpa_event_i_0734f6_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['profile', 'status'], name='geo_eventpa_profile_25054f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together={('event', 'profile')},
        ),
        migrations.AddIndex(
            model_name='openskymission',
            index=models.Index(fields=['status', 'uploaded_at'], name='geo_opensky_status_075d77_idx'),
        ),
        migrations.AddIndex(
            model_name='openskymission',
            index=models.Index(fields=['pilot', 'status'], name='geo_opensky_pilot_i_bd3177_idx'),
        ),
        migrations.AddIndex(
            model_name='openskymission',
            index=models.Index(fields=['hex_q', 'hex_r'], name='geo_opensky_hex_q_ee333c_idx'),
        ),
        migrations.AddIndex(
            model_name='openskytilelayer',
            index=models.Index(fields=['z', 'x', 'y'], name='geo_opensky_z_ecf3d3_idx'),
        ),
        migrations.AddIndex(
            model_name='openskytilelayer',
            index=models.Index(fields=['mission'], name='geo_opensky_mission_886c53_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='openskytilelayer',
            unique_together={('z', 'x', 'y', 'mission')},
        ),
        migrations.AlterUniqueTogether(
            name='quotapayment',
            unique_together={('fraction', 'month')},
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('agency', 'source_id'), name='unique_agency_route'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(condition=models.Q(('place__isnull', False), models.Q(('slug', ''), _negated=True)), fields=('place', 'slug'), name='unique_place_route_slug'),
        ),
        migrations.AddConstraint(
            model_name='stop',
            constraint=models.UniqueConstraint(fields=('agency', 'source_id'), name='unique_agency_stop'),
        ),
        migrations.AddConstraint(
            model_name='stop',
            constraint=models.UniqueConstraint(condition=models.Q(('place__isnull', False), models.Q(('slug', ''), _negated=True)), fields=('place', 'slug'), name='unique_place_stop_slug'),
        ),
        migrations.AddIndex(
            model_name='routestop',
            index=models.Index(fields=['stop', 'direction_id', 'sequence'], name='geo_routest_stop_id_ed9135_idx'),
        ),
        migrations.AddIndex(
            model_name='routestop',
            index=models.Index(fields=['route', 'direction_id', 'sequence'], name='geo_routest_route_i_2578b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(fields=('route', 'stop', 'direction_id'), name='unique_routestop_dir'),
        ),
        migrations.AddIndex(
            model_name='drivershift',
            index=models.Index(fields=['profile', 'status'], name='geo_drivers_profile_f5d3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='drivershift',
            index=models.Index(fields=['route', 'status'], name='geo_drivers_route_i_ed3c40_idx'),
        ),
        migrations.AddIndex(
            model_name='agency',
            index=models.Index(fields=['source_id'], name='geo_agency_source__f604e2_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['route', 'direction_id'], name='geo_trip_route_i_38863e_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['service_id', 'route'], name='geo_trip_service_dd3fcd_idx'),
        ),
        migrations.AddIndex(
            model_name='stoptime',
            index=models.Index(fields=['stop', 'departure_time'], name='geo_stoptim_stop_id_6ba4f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stoptime',
            unique_together={('trip', 'stop_sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('agency', 'vehicle_id')},
        ),
        migrations.AddIndex(
            model_name='worldobject',
            index=models.Index(fields=['xeno_source', 'xeno_id'], name='geo_worldob_xeno_so_cbb0b0_idx'),
        ),
        migrations.AddIndex(
            model_name='worldobject',
            index=models.Index(fields=['city', 'street'], name='geo_worldob_city_c9ed49_idx'),
        ),
        migrations.AddIndex(
            model_name='worldobject',
            index=models.Index(fields=['country', 'city'], name='geo_worldob_country_df8d66_idx'),
        ),
        migrations.AddConstraint(
            model_name='worldobject',
            constraint=models.UniqueConstraint(condition=models.Q(('xeno_id', ''), _negated=True), fields=('xeno_source', 'xeno_id'), name='unique_xeno_identity'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'starts_at'], name='geo_event_status_de9c14_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category', 'status'], name='geo_event_categor_8ccf88_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizer', 'status'], name='geo_event_organiz_1b5530_idx'),
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['name'], name='geo_establi_name_cba690_idx'),
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['slug'], name='geo_establi_slug_706896_idx'),
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['category', 'is_active'], name='geo_establi_categor_95e5f0_idx'),
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['world_object', 'is_active'], name='geo_establi_world_o_4fe0a0_idx'),
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['organization_type', 'is_active'], name='geo_establi_organiz_ce65bd_idx'),
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['owner', 'is_active'], name='geo_establi_owner_i_5c69f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='establishment',
            constraint=models.UniqueConstraint(condition=models.Q(('slug', ''), _negated=True), fields=('slug',), name='unique_establishment_slug'),
        ),
    ]
