# Generated by Django 5.2.15 on 2026-07-04 13:39
"""
Squash of geo 0003-0038. 0001 and 0002 must stay as separate migrations and
cannot be folded in here (or into each other): Django broke the cross-app FK
cycle by interleaving initials — market/0001 depends on geo/0001, geo/0002
depends on market/0001, identity/0002 depends on geo/0002, and this squash
depends on identity/0002. Merging any of them re-creates a circular dependency.
This is a terminal state, do not attempt a fuller squash.
"""

import core.models
import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('geo', '0003_shape_dedup'), ('geo', '0004_populate_shapes'), ('geo', '0005_drop_trip_shape_column'), ('geo', '0006_add_odm_origin_field'), ('geo', '0007_opensky_tiles'), ('geo', '0008_establishment_owner_nullable'), ('geo', '0009_opensky_captured_at'), ('geo', '0010_membership_position_title'), ('geo', '0011_opensky_direction_counts'), ('geo', '0012_openskyposeedge'), ('geo', '0013_transitdatasource_motis_input_name'), ('geo', '0014_backfill_motis_input_names'), ('geo', '0015_backfill_septa_motis_input'), ('geo', '0016_openskymission_license_and_more'), ('geo', '0017_openskymission_place_label_and_more'), ('geo', '0018_openskymission_is_consolidation_and_more'), ('geo', '0019_openskymission_corr_dx_m_openskymission_corr_dy_m_and_more'), ('geo', '0020_openskyposeedge_similarity_db_defaults'), ('geo', '0021_route_line_id_route_line_long_name_route_path_type'), ('geo', '0022_transitdatasource_rt_kind'), ('geo', '0023_openskymission_georef_changed_at_and_more'), ('geo', '0024_stopgroup_stop_group_and_more'), ('geo', '0025_stoptime_departure_secs'), ('geo', '0026_remove_stoptime_id_stoptime_pk'), ('geo', '0027_dronezone'), ('geo', '0028_stop_tts_name'), ('geo', '0029_feedhealthsample'), ('geo', '0030_transitdatasource_generate_shapes'), ('geo', '0031_urbancondicionante_urbanordenamento'), ('geo', '0032_urbanrule'), ('geo', '0033_urbanrule_artigo_usos_urbanrule_usos_dominantes'), ('geo', '0034_urbanrule_source_quote'), ('geo', '0035_urbanrulesignoff'), ('geo', '0036_urbanrule_uso_default_regime_and_more'), ('geo', '0037_territory'), ('geo', '0038_alter_stoptime_stop')]

    dependencies = [
        ('geo', '0002_initial'),
        ('identity', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('source_id', models.CharField(blank=True, db_index=True, help_text='GTFS shape_id', max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(geography=True, srid=4326)),
                ('length_m', models.FloatField(default=0, help_text='Precomputed ST_Length(geography)')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapes', to='geo.agency')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='shape_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='geo.shape'),
        ),
        migrations.AddConstraint(
            model_name='shape',
            constraint=models.UniqueConstraint(condition=models.Q(('source_id', ''), _negated=True), fields=('agency', 'source_id'), name='unique_agency_shape'),
        ),
        migrations.RemoveField(
            model_name='trip',
            name='shape',
        ),
        migrations.AddField(
            model_name='openskymission',
            name='odm_origin',
            field=models.JSONField(blank=True, help_text='ODM origin {x, y, z} in UTM meters + EPSG code', null=True),
        ),
        migrations.RemoveIndex(
            model_name='openskymission',
            name='geo_opensky_hex_q_ee333c_idx',
        ),
        migrations.RemoveField(
            model_name='openskymission',
            name='hex_q',
        ),
        migrations.RemoveField(
            model_name='openskymission',
            name='hex_r',
        ),
        migrations.AddField(
            model_name='openskymission',
            name='tile_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openskymission',
            name='tile_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openskymission',
            name='tile_z',
            field=models.SmallIntegerField(blank=True, default=17, null=True),
        ),
        migrations.AlterField(
            model_name='openskymission',
            name='processing_step',
            field=models.CharField(blank=True, choices=[('odm', 'Running ODM'), ('reprojection', 'Reprojecting'), ('alignment', 'Aligning'), ('tiling', 'Generating tiles'), ('mesh', 'Generating 3D mesh'), ('finalizing', 'Finalizing')], default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='openskymission',
            index=models.Index(fields=['tile_z', 'tile_x', 'tile_y'], name='geo_opensky_tile_z_8d2778_idx'),
        ),
        migrations.AddField(
            model_name='openskymission',
            name='captured_at',
            field=models.DateTimeField(blank=True, help_text='Earliest photo EXIF DateTimeOriginal', null=True),
        ),
        migrations.AddField(
            model_name='openskymission',
            name='direction_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transitdatasource',
            name='motis_input_name',
            field=models.CharField(blank=True, default='', help_text='Filename inside /opt/motis/input/ to sync the fresh GTFS ZIP to. Empty = not synced to MOTIS.', max_length=64),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Profile that manages this establishment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establishments', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='establishmentmembership',
            name='position_title',
            field=models.CharField(blank=True, default='', help_text='Custom position title (e.g. Vice-Presidente, Secretário) — shown instead of generic role label', max_length=100),
        ),
        migrations.AddField(
            model_name='openskymission',
            name='license',
            field=models.CharField(default='CC-BY-SA-4.0', help_text='License of uploaded imagery + derived ortho/mesh/tiles', max_length=32),
        ),
        migrations.AddField(
            model_name='openskymission',
            name='license_consent_at',
            field=models.DateTimeField(blank=True, help_text='When the pilot accepted the imagery license terms at upload', null=True),
        ),
        migrations.AddField(
            model_name='openskymission',
            name='place_label',
            field=models.CharField(blank=True, default='', help_text='Area name (parish/municipality) for the mission card readout', max_length=120),
        ),
        migrations.AddField(
            model_name='openskymission',
            name='place_region',
            field=models.CharField(blank=True, default='', help_text='Region · country subtitle for the mission card readout', max_length=120),
        ),
        migrations.AddField(
            model_name='openskymission',
            name='is_consolidation',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this row is a split-merge super-tile, not a single flight'),
        ),
        migrations.AddField(
            model_name='openskymission',
            name='superseded_by',
            field=models.ForeignKey(blank=True, help_text='If set, this mission is a member of a consolidation and its tiles are overridden by it', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_members', to='geo.openskymission'),
        ),
        migrations.CreateModel(
            name='OpenSkyConsolidationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(help_text='Image filename prefix for this member in the joint ODM project', max_length=16)),
                ('order', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('consolidation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='geo.openskymission')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidation_links', to='geo.openskymission')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['consolidation'], name='geo_opensky_consoli_7f053b_idx'), models.Index(fields=['member'], name='geo_opensky_member__d0c063_idx')],
                'unique_together': {('consolidation', 'member')},
            },
        ),
        migrations.AddField(
            model_name='openskymission',
            name='corr_dx_m',
            field=models.FloatField(default=0.0, help_text='X translation correction last applied (m, EPSG:3857)'),
        ),
        migrations.AddField(
            model_name='openskymission',
            name='corr_dy_m',
            field=models.FloatField(default=0.0, help_text='Y translation correction last applied (m, EPSG:3857)'),
        ),
        migrations.AddField(
            model_name='openskymission',
            name='corr_ln_scale',
            field=models.FloatField(default=0.0, help_text='ln(scale) correction last applied (0 = none)'),
        ),
        migrations.AddField(
            model_name='openskymission',
            name='corr_rotation_deg',
            field=models.FloatField(default=0.0, help_text='Rotation correction last applied (deg, 0 = none)'),
        ),
        migrations.CreateModel(
            name='OpenSkyPoseEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_type', models.CharField(choices=[('orb_pair', 'ORB feature match vs another mission'), ('satellite_anchor', 'ECC alignment vs satellite imagery (absolute anchor)')], db_index=True, max_length=20)),
                ('dx_m', models.FloatField(help_text='X shift (m, EPSG:3857) to apply to mission_a to align with mission_b (or absolute frame)')),
                ('dy_m', models.FloatField(help_text='Y shift (m, EPSG:3857) to apply to mission_a to align with mission_b (or absolute frame)')),
                ('weight', models.FloatField(default=1.0, help_text='Solver weight (e.g. overlap area for ORB)')),
                ('confidence', models.FloatField(default=1.0, help_text='Observation quality (RANSAC inlier ratio for ORB, ECC correlation for satellite)')),
                ('overlap_area_m2', models.FloatField(default=0, help_text='Geographic intersection area (ORB only)')),
                ('measured_at', models.DateTimeField(auto_now=True)),
                ('mission_a', models.ForeignKey(help_text='Mission whose position is being measured (perspective).', on_delete=django.db.models.deletion.CASCADE, related_name='pose_edges_outgoing', to='geo.openskymission')),
                ('mission_b', models.ForeignKey(blank=True, help_text='Reference neighbor. NULL for SATELLITE_ANCHOR (absolute frame).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pose_edges_incoming', to='geo.openskymission')),
                ('rel_rotation_deg', models.FloatField(default=0.0, help_text='Relative rotation (deg, map frame) of mission_a vs mission_b (ORB only)')),
                ('rel_scale', models.FloatField(default=1.0, help_text='Relative scale s_ij of mission_a vs mission_b (ORB only)')),
            ],
            options={
                'indexes': [models.Index(fields=['mission_a', 'edge_type'], name='geo_opensky_mission_4f2326_idx'), models.Index(fields=['mission_b', 'edge_type'], name='geo_opensky_mission_ccedf1_idx')],
                'constraints': [models.UniqueConstraint(fields=('mission_a', 'mission_b', 'edge_type'), name='unique_pose_edge')],
            },
        ),
        migrations.RunSQL(
            sql='ALTER TABLE geo_openskyposeedge ALTER COLUMN rel_scale SET DEFAULT 1.0;ALTER TABLE geo_openskyposeedge ALTER COLUMN rel_rotation_deg SET DEFAULT 0.0;',
            reverse_sql='ALTER TABLE geo_openskyposeedge ALTER COLUMN rel_scale DROP DEFAULT;ALTER TABLE geo_openskyposeedge ALTER COLUMN rel_rotation_deg DROP DEFAULT;',
        ),
        migrations.AddField(
            model_name='route',
            name='line_long_name',
            field=models.CharField(blank=True, help_text='Public line name (GTFS line_long_name ext)', max_length=255),
        ),
        migrations.AddField(
            model_name='route',
            name='path_type',
            field=models.SmallIntegerField(default=0, help_text='Variant order within line (GTFS path_type ext); lowest = canonical'),
        ),
        migrations.AddField(
            model_name='transitdatasource',
            name='rt_kind',
            field=models.CharField(choices=[('gps', 'GPS vehicle positions'), ('arrivals', 'Arrival predictions'), ('none', 'No realtime')], default='gps', help_text='Realtime delivery model: gps=GTFS-RT VehiclePositions (default), arrivals=bespoke arrival-time API with no GPS (metro/rail), none=static only', max_length=16),
        ),
        migrations.AddField(
            model_name='openskymission',
            name='georef_changed_at',
            field=models.DateTimeField(blank=True, help_text='Last physical georef change of the saved ortho', null=True),
        ),
        migrations.AddField(
            model_name='openskyposeedge',
            name='ref_x_3857',
            field=models.FloatField(blank=True, help_text='X of the translation reference point (m, EPSG:3857)', null=True),
        ),
        migrations.AddField(
            model_name='openskyposeedge',
            name='ref_y_3857',
            field=models.FloatField(blank=True, help_text='Y of the translation reference point (m, EPSG:3857)', null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='line_id',
            field=models.CharField(blank=True, db_index=True, help_text='External line ID grouping route variants (GTFS line_id ext)', max_length=100),
        ),
        migrations.CreateModel(
            name='StopGroup',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('name', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Centroid of member unit roots', srid=4326)),
                ('member_count', models.PositiveSmallIntegerField(default=0, help_text='Physical platforms/poles (location_type=0) in the group')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stop_groups', to='geo.place')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stop',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Virtual stop this physical stop belongs to (recomputed, never authored)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stops', to='geo.stopgroup'),
        ),
        migrations.AddIndex(
            model_name='stopgroup',
            index=django.contrib.postgres.indexes.GinIndex(fields=['attributes'], name='geo_stopgro_attribu_30714f_gin'),
        ),
        migrations.AddIndex(
            model_name='stopgroup',
            index=django.contrib.postgres.indexes.GinIndex(fields=['relations'], name='geo_stopgro_relatio_0f2f57_gin'),
        ),
        migrations.AddField(
            model_name='stoptime',
            name='departure_secs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='stoptime',
            name='id',
        ),
        migrations.AddField(
            model_name='stoptime',
            name='pk',
            field=models.CompositePrimaryKey('trip', 'stop_sequence', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='DroneZone',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('source', models.CharField(db_index=True, default='anac_pt', help_text="Data provider key, e.g. 'anac_pt'", max_length=32)),
                ('source_version', models.CharField(blank=True, help_text='Provider dataset version stamp', max_length=64)),
                ('zone_identifier', models.CharField(db_index=True, help_text="ED-269 feature identifier (e.g. '1001UA')", max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(default='PRT', max_length=3)),
                ('restriction', models.CharField(choices=[('PROHIBITED', 'Prohibited'), ('REQ_AUTHORISATION', 'Authorisation required'), ('CONDITIONAL', 'Conditional'), ('NO_RESTRICTION', 'No restriction')], db_index=True, default='REQ_AUTHORISATION', max_length=20)),
                ('reason', models.JSONField(blank=True, default=list, help_text="ED-269 reason codes, e.g. ['AIR_TRAFFIC']")),
                ('message', models.TextField(blank=True)),
                ('lower_limit_m', models.FloatField(default=0, help_text='Lower vertical limit, metres')),
                ('upper_limit_m', models.FloatField(default=120, help_text='Upper vertical limit, metres')),
                ('lower_ref', models.CharField(default='AGL', help_text='AGL or AMSL', max_length=8)),
                ('upper_ref', models.CharField(default='AGL', help_text='AGL or AMSL', max_length=8)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, help_text='Zone footprint (ED-269 circles buffered to polygons)', srid=4326)),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'restriction'], name='geo_dronezo_source_399827_idx')],
            },
        ),
        migrations.AddField(
            model_name='stop',
            name='tts_name',
            field=models.CharField(blank=True, default='', help_text='GTFS tts_stop_name: unabbreviated form for text-to-speech (driver-mode announcements, screen readers). Empty when the feed omits it.', max_length=255),
        ),
        migrations.CreateModel(
            name='FeedHealthSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('ok', 'OK (serving live data)'), ('idle', 'Idle (no vehicles — off-service)'), ('stale', 'Stale (frozen data despite HTTP 200)'), ('unreachable', 'Unreachable (fetch failed)')], max_length=12)),
                ('fresh_count', models.PositiveIntegerField(default=0, help_text='Vehicles fresher than 180s (transit:members)')),
                ('total_served', models.PositiveIntegerField(default=0, help_text='Vehicles in the unfiltered feed mirror')),
                ('freshest_age_s', models.PositiveIntegerField(blank=True, help_text='Age of the freshest fix, seconds', null=True)),
                ('detail', models.CharField(blank=True, help_text='last_error text (unreachable) or note', max_length=300)),
                ('data_source', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='health_samples', to='geo.transitdatasource')),
            ],
            options={
                'db_table': 'geo_feedhealthsample',
                'indexes': [models.Index(fields=['data_source', 'time'], name='feedhealth_ds_time_idx')],
            },
        ),
        migrations.AddField(
            model_name='transitdatasource',
            name='generate_shapes',
            field=models.BooleanField(default=False, help_text='Synthesize shapes.txt with pfaedle (map-match trips onto OSM track geometry) during update when the upstream feed ships none. For rail feeds whose trips reference shape_id but omit shapes.txt (e.g. CP).'),
        ),
        migrations.CreateModel(
            name='UrbanCondicionante',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('municipio', models.CharField(db_index=True, max_length=64)),
                ('source', models.CharField(db_index=True, default='caminha_munisig', max_length=64)),
                ('source_version', models.CharField(blank=True, help_text='Data snapshot / plan version stamp', max_length=64)),
                ('service_layer', models.CharField(blank=True, help_text="Provenance: source service + layer id, e.g. 'CONDICIONANTES/23'", max_length=128)),
                ('grupo', models.CharField(blank=True, db_index=True, help_text="Condicionante group, e.g. 'Recursos Naturais'", max_length=128)),
                ('tipo', models.CharField(blank=True, db_index=True, help_text="Condicionante type = layer name, e.g. 'Reserva Ecológica Nacional'", max_length=255)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(help_text='Condicionante geometry (mixed point/line/polygon, WGS84)', srid=4326)),
                ('ingested_at', models.DateTimeField(db_index=True, help_text='When this batch was loaded')),
            ],
            options={
                'indexes': [models.Index(fields=['municipio', 'tipo'], name='geo_urbanco_municip_facfea_idx')],
            },
        ),
        migrations.CreateModel(
            name='UrbanOrdenamento',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('municipio', models.CharField(db_index=True, help_text="Município slug, e.g. 'caminha'", max_length=64)),
                ('source', models.CharField(db_index=True, default='caminha_munisig', help_text='ETL adapter / SIG portal the data was ingested from', max_length=64)),
                ('source_version', models.CharField(blank=True, help_text="Data snapshot / plan version stamp, e.g. 'munisig-2026-06-30'", max_length=64)),
                ('service_layer', models.CharField(blank=True, help_text="Provenance: source service + layer id, e.g. 'ORDENAMENTO/12'", max_length=128)),
                ('classe', models.CharField(blank=True, db_index=True, help_text="Classe do solo: 'Solo Urbano' | 'Solo Rústico'", max_length=128)),
                ('categoria', models.CharField(blank=True, help_text='Categoria de uso do solo (regulamento quadro de usos)', max_length=255)),
                ('subcategoria', models.CharField(blank=True, max_length=255)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Curated source attributes (e.g. area_ha) for traceability')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(help_text='Ordenamento polygon (WGS84)', srid=4326)),
                ('ingested_at', models.DateTimeField(db_index=True, help_text='When this batch was loaded')),
            ],
            options={
                'indexes': [models.Index(fields=['municipio', 'classe'], name='geo_urbanor_municip_098c69_idx')],
            },
        ),
        migrations.CreateModel(
            name='UrbanRuleSignoff',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('municipio', models.CharField(db_index=True, max_length=64)),
                ('source', models.CharField(help_text='Rule-bundle source key this confirmation attests (UrbanRule.source)', max_length=64)),
                ('categoria', models.CharField(max_length=255)),
                ('subcategoria', models.CharField(blank=True, max_length=255)),
                ('signed_snapshot', models.JSONField(default=dict, help_text='Rule parameters as shown when signed; compared to current to flag staleness')),
                ('signed_at', models.DateTimeField(help_text='When this confirmation was recorded / last refreshed')),
                ('account', models.ForeignKey(help_text='The validator who signed', on_delete=django.db.models.deletion.CASCADE, related_name='urban_rule_signoffs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['municipio', 'source'], name='geo_urbanru_municip_8868f8_idx')],
                'unique_together': {('municipio', 'source', 'categoria', 'subcategoria', 'account')},
            },
        ),
        migrations.CreateModel(
            name='UrbanRule',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('municipio', models.CharField(db_index=True, max_length=64)),
                ('source', models.CharField(db_index=True, default='caminha_pdm_reg', help_text='Curation source key (regulamento the rules were transcribed from)', max_length=64)),
                ('source_version', models.CharField(blank=True, help_text="Plan/regulamento version, e.g. 'aviso-4482-2024'", max_length=64)),
                ('categoria', models.CharField(db_index=True, max_length=255)),
                ('subcategoria', models.CharField(blank=True, db_index=True, max_length=255)),
                ('diploma', models.CharField(blank=True, help_text="e.g. 'DR 2.ª série N.º 41, 27-02-2024, Aviso n.º 4482/2024'", max_length=255)),
                ('artigo', models.CharField(blank=True, help_text="e.g. '54.º'", max_length=32)),
                ('indice_utilizacao', models.DecimalField(blank=True, decimal_places=2, help_text='Índice de utilização do solo (m²/m²): área de construção / área do solo', max_digits=5, null=True)),
                ('indice_utilizacao_max', models.BooleanField(default=True, help_text="True = 'máximo'; False = 'de referência' (regulamento wording)")),
                ('indice_impermeabilizacao_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Índice máximo de impermeabilização (%)', max_digits=5, null=True)),
                ('num_pisos_max', models.PositiveSmallIntegerField(blank=True, help_text='N.º máximo de pisos acima da cota de soleira', null=True)),
                ('cercea_max_m', models.DecimalField(blank=True, decimal_places=2, help_text='Cércea máxima (m), where the plan fixes one', max_digits=5, null=True)),
                ('edificavel', models.BooleanField(default=True, help_text='False / restricted regime (e.g. espaços verdes — apoio only)')),
                ('notes', models.TextField(blank=True, help_text='Source-derived regime text (PT) for non-numeric rules; authoritative')),
                ('ingested_at', models.DateTimeField(db_index=True, help_text='When this batch was loaded')),
                ('artigo_usos', models.CharField(blank=True, help_text="Artigo of the Caracterização/usos provision (e.g. '53.º'), where it differs from the Edificabilidade artigo", max_length=32)),
                ('usos_dominantes', models.JSONField(blank=True, default=list, help_text='Dominant/permitido use slugs (quadro de usos)')),
                ('source_quote', models.TextField(blank=True, help_text='Verbatim regulamento sentence(s) establishing the índices/usos/edificável above, artigo-prefixed — the provenance a licensed urbanista check-marks (Gate-L2). Completes the citation: value sits next to the words that fix it')),
                ('uso_default_regime', models.CharField(blank=True, choices=[('condicionado', 'condicionado'), ('interdito', 'interdito')], help_text="Curated regime for uses NOT in usos_dominantes, per the regulamento's own wording; blank = not curated (non-listed uses stay un-adjudicated)", max_length=16)),
            ],
            options={
                'indexes': [models.Index(fields=['municipio', 'categoria', 'subcategoria'], name='geo_urbanru_municip_b0c3e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('level', models.CharField(choices=[('country', 'Country'), ('region', 'Region'), ('municipality', 'Municipality'), ('parish', 'Parish')], db_index=True, max_length=20)),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-2; equals code for country rows', max_length=2)),
                ('code', models.CharField(help_text='Official code: ISO alpha-2 (country), NUTS II (region), DICO (PT municipality), DICOFRE (PT parish)', max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, help_text='Simplified boundary, optional (future residency auto-suggest)', null=True, srid=4326)),
                ('is_active', models.BooleanField(default=True, help_text='False for territories dissolved by administrative reforms')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='geo.territory')),
            ],
            options={
                'verbose_name_plural': 'territories',
                'db_table': 'geo_territory',
                'indexes': [models.Index(fields=['country', 'level'], name='geo_territo_country_778f2d_idx'), models.Index(fields=['parent'], name='geo_territo_parent__e7497d_idx')],
                'unique_together': {('country', 'level', 'code')},
            },
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='stop',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='geo.stop'),
        ),
    ]
