# Generated by Django 5.2.12 on 2026-04-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_drop_trip_shape_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='openskymission',
            name='odm_origin',
            field=models.JSONField(blank=True, help_text='ODM origin {x, y, z} in UTM meters + EPSG code', null=True),
        ),
    ]
