# Generated by Django 5.2.12 on 2026-04-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_add_odm_origin_field'),
        ('identity', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='openskymission',
            name='geo_opensky_hex_q_ee333c_idx',
        ),
        migrations.RemoveField(
            model_name='openskymission',
            name='hex_q',
        ),
        migrations.RemoveField(
            model_name='openskymission',
            name='hex_r',
        ),
        migrations.AddField(
            model_name='openskymission',
            name='tile_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openskymission',
            name='tile_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openskymission',
            name='tile_z',
            field=models.SmallIntegerField(blank=True, default=17, null=True),
        ),
        migrations.AlterField(
            model_name='openskymission',
            name='processing_step',
            field=models.CharField(blank=True, choices=[('odm', 'Running ODM'), ('reprojection', 'Reprojecting'), ('alignment', 'Aligning'), ('tiling', 'Generating tiles'), ('mesh', 'Generating 3D mesh'), ('finalizing', 'Finalizing')], default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='openskymission',
            index=models.Index(fields=['tile_z', 'tile_x', 'tile_y'], name='geo_opensky_tile_z_8d2778_idx'),
        ),
    ]
