# Generated by Django 5.2.12 on 2026-04-06 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_opensky_tiles'),
        ('identity', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Profile that manages this establishment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establishments', to='identity.profile'),
        ),
    ]
