# Generated by Django 5.2.12 on 2026-04-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0008_establishment_owner_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='openskymission',
            name='captured_at',
            field=models.DateTimeField(blank=True, help_text='Earliest photo EXIF DateTimeOriginal', null=True),
        ),
    ]
