# Generated by Django 5.2.12 on 2026-04-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0009_opensky_captured_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishmentmembership',
            name='position_title',
            field=models.CharField(blank=True, default='', help_text='Custom position title (e.g. Vice-Presidente, Secretário) — shown instead of generic role label', max_length=100),
        ),
    ]
