# Generated by Django 5.2.12 on 2026-04-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0010_membership_position_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='openskymission',
            name='direction_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
