# Generated by Django 5.2.12 on 2026-04-19 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0011_opensky_direction_counts'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSkyPoseEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_type', models.CharField(choices=[('orb_pair', 'ORB feature match vs another mission'), ('satellite_anchor', 'ECC alignment vs satellite imagery (absolute anchor)')], db_index=True, max_length=20)),
                ('dx_m', models.FloatField(help_text='X shift (m, EPSG:3857) to apply to mission_a to align with mission_b (or absolute frame)')),
                ('dy_m', models.FloatField(help_text='Y shift (m, EPSG:3857) to apply to mission_a to align with mission_b (or absolute frame)')),
                ('weight', models.FloatField(default=1.0, help_text='Solver weight (e.g. overlap area for ORB)')),
                ('confidence', models.FloatField(default=1.0, help_text='Observation quality (RANSAC inlier ratio for ORB, ECC correlation for satellite)')),
                ('overlap_area_m2', models.FloatField(default=0, help_text='Geographic intersection area (ORB only)')),
                ('measured_at', models.DateTimeField(auto_now=True)),
                ('mission_a', models.ForeignKey(help_text='Mission whose position is being measured (perspective).', on_delete=django.db.models.deletion.CASCADE, related_name='pose_edges_outgoing', to='geo.openskymission')),
                ('mission_b', models.ForeignKey(blank=True, help_text='Reference neighbor. NULL for SATELLITE_ANCHOR (absolute frame).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pose_edges_incoming', to='geo.openskymission')),
            ],
            options={
                'indexes': [models.Index(fields=['mission_a', 'edge_type'], name='geo_opensky_mission_4f2326_idx'), models.Index(fields=['mission_b', 'edge_type'], name='geo_opensky_mission_ccedf1_idx')],
                'constraints': [models.UniqueConstraint(fields=('mission_a', 'mission_b', 'edge_type'), name='unique_pose_edge')],
            },
        ),
    ]
