# Generated by Django 5.2.14 on 2026-05-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0012_openskyposeedge'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitdatasource',
            name='motis_input_name',
            field=models.CharField(blank=True, default='', help_text='Filename inside /opt/motis/input/ to sync the fresh GTFS ZIP to. Empty = not synced to MOTIS.', max_length=64),
        ),
    ]
