# Generated by Django 5.2.14 on 2026-05-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0015_backfill_septa_motis_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='openskymission',
            name='license',
            field=models.CharField(default='CC-BY-SA-4.0', help_text='License of uploaded imagery + derived ortho/mesh/tiles', max_length=32),
        ),
        migrations.AddField(
            model_name='openskymission',
            name='license_consent_at',
            field=models.DateTimeField(blank=True, help_text='When the pilot accepted the imagery license terms at upload', null=True),
        ),
    ]
