# Generated by Django 5.2.14 on 2026-06-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0016_openskymission_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openskymission',
            name='place_label',
            field=models.CharField(blank=True, default='', help_text='Area name (parish/municipality) for the mission card readout', max_length=120),
        ),
        migrations.AddField(
            model_name='openskymission',
            name='place_region',
            field=models.CharField(blank=True, default='', help_text='Region · country subtitle for the mission card readout', max_length=120),
        ),
    ]
