# Generated by Django 5.2.14 on 2026-06-09 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0017_openskymission_place_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openskymission',
            name='is_consolidation',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this row is a split-merge super-tile, not a single flight'),
        ),
        migrations.AddField(
            model_name='openskymission',
            name='superseded_by',
            field=models.ForeignKey(blank=True, help_text='If set, this mission is a member of a consolidation and its tiles are overridden by it', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_members', to='geo.openskymission'),
        ),
        migrations.CreateModel(
            name='OpenSkyConsolidationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(help_text='Image filename prefix for this member in the joint ODM project', max_length=16)),
                ('order', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('consolidation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='geo.openskymission')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidation_links', to='geo.openskymission')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['consolidation'], name='geo_opensky_consoli_7f053b_idx'), models.Index(fields=['member'], name='geo_opensky_member__d0c063_idx')],
                'unique_together': {('consolidation', 'member')},
            },
        ),
    ]
