# Generated by Django 5.2.14 on 2026-06-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0018_openskymission_is_consolidation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openskymission',
            name='corr_dx_m',
            field=models.FloatField(default=0.0, help_text='X translation correction last applied (m, EPSG:3857)'),
        ),
        migrations.AddField(
            model_name='openskymission',
            name='corr_dy_m',
            field=models.FloatField(default=0.0, help_text='Y translation correction last applied (m, EPSG:3857)'),
        ),
        migrations.AddField(
            model_name='openskymission',
            name='corr_ln_scale',
            field=models.FloatField(default=0.0, help_text='ln(scale) correction last applied (0 = none)'),
        ),
        migrations.AddField(
            model_name='openskymission',
            name='corr_rotation_deg',
            field=models.FloatField(default=0.0, help_text='Rotation correction last applied (deg, 0 = none)'),
        ),
        migrations.AddField(
            model_name='openskyposeedge',
            name='rel_rotation_deg',
            field=models.FloatField(default=0.0, help_text='Relative rotation (deg, map frame) of mission_a vs mission_b (ORB only)'),
        ),
        migrations.AddField(
            model_name='openskyposeedge',
            name='rel_scale',
            field=models.FloatField(default=1.0, help_text='Relative scale s_ij of mission_a vs mission_b (ORB only)'),
        ),
    ]
