# Generated by Django 5.2.14 on 2026-06-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0020_openskyposeedge_similarity_db_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='line_id',
            field=models.CharField(blank=True, db_index=True, help_text='External line ID grouping route variants (GTFS line_id ext)', max_length=100),
        ),
        migrations.AddField(
            model_name='route',
            name='line_long_name',
            field=models.CharField(blank=True, help_text='Public line name (GTFS line_long_name ext)', max_length=255),
        ),
        migrations.AddField(
            model_name='route',
            name='path_type',
            field=models.SmallIntegerField(default=0, help_text='Variant order within line (GTFS path_type ext); lowest = canonical'),
        ),
    ]
