# Generated by Django 5.2.14 on 2026-06-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0021_route_line_id_route_line_long_name_route_path_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitdatasource',
            name='rt_kind',
            field=models.CharField(choices=[('gps', 'GPS vehicle positions'), ('arrivals', 'Arrival predictions'), ('none', 'No realtime')], default='gps', help_text='Realtime delivery model: gps=GTFS-RT VehiclePositions (default), arrivals=bespoke arrival-time API with no GPS (metro/rail), none=static only', max_length=16),
        ),
    ]
