# Generated by Django 5.2.14 on 2026-06-11 14:13

from django.db import migrations, models
from django.utils import timezone


def backfill_georef_changed_at(apps, schema_editor):
    """Stamp every existing mission as 'georef just changed'.

    Existing pose edges were measured against ortho states that have since been
    warped (Phase-2 similarity, 2026-06-10/11) — under the new delta semantics
    they describe a frame that no longer exists. Backfilling now() marks them
    ALL stale, which forces a `measure_opensky_edges` pass before the next
    Phase-2 solve instead of silently re-deriving already-applied corrections.
    """
    OpenSkyMission = apps.get_model('geo', 'OpenSkyMission')
    OpenSkyMission.objects.update(georef_changed_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0022_transitdatasource_rt_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='openskymission',
            name='georef_changed_at',
            field=models.DateTimeField(blank=True, help_text='Last physical georef change of the saved ortho', null=True),
        ),
        migrations.AddField(
            model_name='openskyposeedge',
            name='ref_x_3857',
            field=models.FloatField(blank=True, help_text='X of the translation reference point (m, EPSG:3857)', null=True),
        ),
        migrations.AddField(
            model_name='openskyposeedge',
            name='ref_y_3857',
            field=models.FloatField(blank=True, help_text='Y of the translation reference point (m, EPSG:3857)', null=True),
        ),
        migrations.RunPython(backfill_georef_changed_at, migrations.RunPython.noop),
    ]
