# Generated by Django 5.2.14 on 2026-06-12 14:46

import core.models
import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0023_openskymission_georef_changed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopGroup',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('name', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Centroid of member unit roots', srid=4326)),
                ('member_count', models.PositiveSmallIntegerField(default=0, help_text='Physical platforms/poles (location_type=0) in the group')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stop_groups', to='geo.place')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stop',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Virtual stop this physical stop belongs to (recomputed, never authored)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stops', to='geo.stopgroup'),
        ),
        migrations.AddIndex(
            model_name='stopgroup',
            index=django.contrib.postgres.indexes.GinIndex(fields=['attributes'], name='geo_stopgro_attribu_30714f_gin'),
        ),
        migrations.AddIndex(
            model_name='stopgroup',
            index=django.contrib.postgres.indexes.GinIndex(fields=['relations'], name='geo_stopgro_relatio_0f2f57_gin'),
        ),
    ]
