# Generated by Django 5.2.14 on 2026-06-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0024_stopgroup_stop_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoptime',
            name='departure_secs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
