# Generated by Django 5.2.14 on 2026-06-13 15:07
#
# Drop StopTime's synthetic BigAutoField `id` PK in favour of a composite PK on
# (trip, stop_sequence) — already the unique_together natural key. StopTime is
# never looked up by surrogate id (all reads filter trip/stop/departure_time +
# stop_sequence), so the id index was ~1.4 GB of dead weight on 41M rows.
#
# At the DB level this is a single `DROP COLUMN id CASCADE` (drops the column +
# its pkey index) — a fast metadata op, no table rewrite, no long lock. The
# existing (trip, stop_sequence) UNIQUE constraint/index (4.2 GB) is KEPT as the
# key, so the CompositePrimaryKey is an ORM-level construct over it (no rebuild).
# The AddField(pk) below is therefore a DB no-op.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0025_stoptime_departure_secs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoptime',
            name='id',
        ),
        migrations.AddField(
            model_name='stoptime',
            name='pk',
            field=models.CompositePrimaryKey('trip', 'stop_sequence', blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
