# Generated by Django 5.2.14 on 2026-06-14 11:25

import core.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0026_remove_stoptime_id_stoptime_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneZone',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('source', models.CharField(db_index=True, default='anac_pt', help_text="Data provider key, e.g. 'anac_pt'", max_length=32)),
                ('source_version', models.CharField(blank=True, help_text='Provider dataset version stamp', max_length=64)),
                ('zone_identifier', models.CharField(db_index=True, help_text="ED-269 feature identifier (e.g. '1001UA')", max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(default='PRT', max_length=3)),
                ('restriction', models.CharField(choices=[('PROHIBITED', 'Prohibited'), ('REQ_AUTHORISATION', 'Authorisation required'), ('CONDITIONAL', 'Conditional'), ('NO_RESTRICTION', 'No restriction')], db_index=True, default='REQ_AUTHORISATION', max_length=20)),
                ('reason', models.JSONField(blank=True, default=list, help_text="ED-269 reason codes, e.g. ['AIR_TRAFFIC']")),
                ('message', models.TextField(blank=True)),
                ('lower_limit_m', models.FloatField(default=0, help_text='Lower vertical limit, metres')),
                ('upper_limit_m', models.FloatField(default=120, help_text='Upper vertical limit, metres')),
                ('lower_ref', models.CharField(default='AGL', help_text='AGL or AMSL', max_length=8)),
                ('upper_ref', models.CharField(default='AGL', help_text='AGL or AMSL', max_length=8)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, help_text='Zone footprint (ED-269 circles buffered to polygons)', srid=4326)),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'restriction'], name='geo_dronezo_source_399827_idx')],
            },
        ),
    ]
