# Generated by Django 5.2.14 on 2026-06-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0027_dronezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='tts_name',
            field=models.CharField(blank=True, default='', help_text='GTFS tts_stop_name: unabbreviated form for text-to-speech (driver-mode announcements, screen readers). Empty when the feed omits it.', max_length=255),
        ),
    ]
