# Generated by Django 5.2.12 on 2026-03-30 10:09

import core.models
import django.db.models.deletion
import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('category', models.CharField(choices=[('EVENT', 'Event ticket'), ('TRANSIT', 'Transit ticket')], db_index=True, max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price_sats', models.PositiveBigIntegerField(help_text='Price in satoshis')),
                ('max_capacity', models.PositiveIntegerField(blank=True, help_text='Max tickets (null = unlimited)', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sold_count', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='geo.event')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operated_ticket_types', to='identity.profile')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='geo.route')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('ACTIVE', 'Active'), ('USED', 'Used'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING_PAYMENT', max_length=20)),
                ('qr_token', models.CharField(db_index=True, default=tickets.models.generate_qr_token, max_length=64, unique=True)),
                ('pgp_signature', models.TextField(blank=True)),
                ('ln_payment_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ln_preimage', models.CharField(blank=True, max_length=64)),
                ('amount_paid_sats', models.PositiveBigIntegerField(default=0)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_tickets', to='identity.profile')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.tickettype')),
            ],
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['event', 'is_active'], name='tickets_tic_event_i_4b23ce_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['route', 'is_active'], name='tickets_tic_route_i_4e20f1_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['category', 'is_active'], name='tickets_tic_categor_24be36_idx'),
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event__isnull', True), ('route__isnull', False)), models.Q(('event__isnull', False), ('route__isnull', True)), _connector='OR'), name='ticket_type_event_xor_route'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['buyer', 'status'], name='tickets_tic_buyer_i_ef0999_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_type', 'status'], name='tickets_tic_ticket__0ca21b_idx'),
        ),
    ]
