# Generated by Django 5.2.14 on 2026-06-12 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0024_stopgroup_stop_group_and_more'),
        ('identity', '0002_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='amount_due_sats',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price_eur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='EUR price snapshot at purchase (fiat-priced types)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='operator_establishment',
            field=models.ForeignKey(blank=True, help_text='Organization operator: receives payment, members manage/validate', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operated_ticket_types', to='geo.establishment'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='price_eur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='EUR price — sats quoted at purchase time (exclusive with price_sats)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='price_sats',
            field=models.PositiveBigIntegerField(blank=True, help_text='Fixed price in satoshis (exclusive with price_eur)', null=True),
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('price_eur__isnull', True), ('price_sats__isnull', False)), models.Q(('price_eur__isnull', False), ('price_sats__isnull', True)), _connector='OR'), name='ticket_type_sats_xor_eur_price'),
        ),
    ]
