# Generated by Django 5.2.14 on 2026-06-12 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0024_stopgroup_stop_group_and_more'),
        ('identity', '0002_initial'),
        ('tickets', '0002_ticket_amount_due_sats_ticket_price_eur_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tickettype',
            name='ticket_type_event_xor_route',
        ),
        migrations.AddField(
            model_name='ticket',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='validation_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Network-wide ticket: valid on any route of this agency', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='geo.agency'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='validity_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Usage window after first validation (null = one-shot: scan marks USED)', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('ACTIVE', 'Active'), ('VALIDATED', 'Validated'), ('USED', 'Used'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING_PAYMENT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['agency', 'is_active'], name='tickets_tic_agency__aca861_idx'),
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agency__isnull', True), ('event__isnull', False), ('route__isnull', True)), models.Q(('agency__isnull', True), ('event__isnull', True), ('route__isnull', False)), models.Q(('agency__isnull', False), ('event__isnull', True), ('route__isnull', True)), _connector='OR'), name='ticket_type_single_target'),
        ),
    ]
