# Generated by Django 5.2.14 on 2026-06-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_tickettype_ticket_type_event_xor_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='refund_payment_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ticket',
            name='refund_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='refund_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='concession_category',
            field=models.CharField(blank=True, choices=[('CHILD', 'Child'), ('STUDENT', 'Student'), ('SENIOR', 'Senior'), ('REDUCED', 'Reduced mobility / social')], help_text='Concession fare label — inspector checks entitlement document on scan', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('ACTIVE', 'Active'), ('VALIDATED', 'Validated'), ('USED', 'Used'), ('REFUND_REQUESTED', 'Refund Requested'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING_PAYMENT', max_length=20),
        ),
    ]
