# Generated by Django 5.2.12 on 2026-03-30 10:09

import core.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyBillingRecord',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('kwh_consumed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_eur', models.DecimalField(decimal_places=4, help_text='1% EGAC management fee', max_digits=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INVOICED', 'Invoiced'), ('PAID', 'Paid')], default='PENDING', max_length=10)),
                ('invoice_reference', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'energy_billing_record',
            },
        ),
        migrations.CreateModel(
            name='EnergyCell',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('transformer_id', models.CharField(blank=True, help_text='E-Redes PT ID', max_length=50)),
                ('radius_km', models.DecimalField(decimal_places=1, default=2.0, max_digits=4)),
                ('status', models.CharField(choices=[('GREEN', 'Green — surplus available'), ('YELLOW', 'Yellow — balanced'), ('RED', 'Red — no surplus'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=10)),
                ('current_price_eur', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'Energy Cell (ACC)',
                'db_table': 'energy_cell',
            },
        ),
        migrations.CreateModel(
            name='EnergyConsumer',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('cpe_code', models.CharField(help_text='CPE code from electricity bill', max_length=30)),
                ('distribution_coefficient', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Energy Consumer (Neighbor)',
                'db_table': 'energy_consumer',
            },
        ),
        migrations.CreateModel(
            name='EnergyProducer',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('cpe_code', models.CharField(help_text='CPE code from electricity bill (e.g. PT0002XXXXXXXXXX)', max_length=30)),
                ('capacity_kw', models.DecimalField(decimal_places=2, help_text='Installed PV capacity in kW', max_digits=6)),
                ('battery_kwh', models.DecimalField(blank=True, decimal_places=2, help_text='Battery capacity in kWh (optional)', max_digits=6, null=True)),
                ('inverter_type', models.CharField(choices=[('SOLARMAN', 'Solarman (Deye/Sofar)'), ('FRONIUS', 'Fronius'), ('GROWATT', 'Growatt'), ('SMA', 'SMA'), ('SHELLY', 'Shelly EM'), ('OTHER', 'Other')], default='OTHER', max_length=12)),
                ('inverter_api_url', models.CharField(blank=True, max_length=255)),
                ('inverter_api_token', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Energy Producer (UPAC)',
                'db_table': 'energy_producer',
            },
        ),
        migrations.CreateModel(
            name='EnergyRelay',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('name', models.CharField(max_length=100)),
                ('relay_type', models.CharField(choices=[('SHELLY_GEN2', 'Shelly Gen2+'), ('SHELLY_GEN1', 'Shelly Gen1'), ('TASMOTA', 'Tasmota')], max_length=12)),
                ('url', models.CharField(max_length=255)),
                ('channel', models.SmallIntegerField(default=0, help_text='Relay channel (0 for single-channel devices)')),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'energy_relay',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GridInfrastructure',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('infrastructure_type', models.CharField(choices=[('transformer', 'Transformer Station (PT)'), ('pole', 'Power Pole'), ('cabinet', 'Distribution Cabinet')], max_length=15)),
                ('eredes_id', models.CharField(max_length=50, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('capacity_kva', models.FloatField(blank=True, null=True)),
                ('voltage_level', models.CharField(blank=True, max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'energy_grid_infrastructure',
            },
        ),
    ]
