# Generated by Django 5.2.12 on 2026-03-30 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('energy', '0001_initial'),
        ('identity', '0001_initial'),
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='energybillingrecord',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_billing', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='energycell',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_energy_cells', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='energybillingrecord',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='energy.energycell'),
        ),
        migrations.AddField(
            model_name='energyconsumer',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumers', to='energy.energycell'),
        ),
        migrations.AddField(
            model_name='energyconsumer',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_consumer_memberships', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='energyconsumer',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='energy_consumers', to='iot.property'),
        ),
        migrations.AddField(
            model_name='energyproducer',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producers', to='energy.energycell'),
        ),
        migrations.AddField(
            model_name='energyproducer',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_producer_memberships', to='identity.profile'),
        ),
        migrations.AddField(
            model_name='energyproducer',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='energy_producers', to='iot.property'),
        ),
        migrations.AddField(
            model_name='energyrelay',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relays', to='energy.energyconsumer'),
        ),
        migrations.AddIndex(
            model_name='energybillingrecord',
            index=models.Index(fields=['profile', '-period_start'], name='energy_bill_profile_741740_idx'),
        ),
        migrations.AddIndex(
            model_name='energybillingrecord',
            index=models.Index(fields=['cell', '-period_start'], name='energy_bill_cell_id_29a844_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='energyconsumer',
            unique_together={('cell', 'profile')},
        ),
        migrations.AlterUniqueTogether(
            name='energyproducer',
            unique_together={('cell', 'profile')},
        ),
    ]
