# Generated by Django 5.2.12 on 2026-04-03 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_initial'),
        ('geo', '0005_drop_trip_shape_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='energycell',
            name='establishment',
            field=models.ForeignKey(blank=True, help_text='Cooperative or organization managing this ACC', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='energy_cells', to='geo.establishment'),
        ),
    ]
