# Generated by Django 5.2.12 on 2026-03-30 10:09

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('token', models.TextField(help_text='FCM registration token', unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], default='android', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fcm_devices',
                'indexes': [models.Index(fields=['user', 'is_active'], name='fcm_devices_user_id_a9778f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('endpoint', models.URLField(help_text='Push service endpoint URL', max_length=500, unique=True)),
                ('p256dh', models.CharField(help_text='Client public key for encryption (p256dh)', max_length=200)),
                ('auth', models.CharField(help_text='Authentication secret', max_length=200)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subscription is active')),
                ('last_sent_at', models.DateTimeField(blank=True, help_text='Last time a notification was sent to this subscription', null=True)),
                ('failed_count', models.IntegerField(default=0, help_text='Number of failed delivery attempts')),
                ('user', models.ForeignKey(help_text='User who owns this push subscription', on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'push_subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='push_subscr_user_id_c81a15_idx'), models.Index(fields=['endpoint'], name='push_subscr_endpoin_48e896_idx')],
            },
        ),
    ]
