# Generated by Django 5.2.15 on 2026-06-21 18:59

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('type', models.CharField(help_text='Event type, e.g. new_booking', max_length=50)),
                ('category', models.CharField(blank=True, help_text='Preference category (social/contracts/governance/calls/rental/…)', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, help_text='Deep link opened on click', max_length=500)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Structured payload (object ids, actor name, …)')),
                ('read_at', models.DateTimeField(blank=True, db_index=True, help_text='When the recipient marked it read; NULL = unread', null=True)),
                ('recipient', models.ForeignKey(help_text='Account that receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_8dcb32_idx'), models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_2d3764_idx'), models.Index(fields=['recipient', 'category'], name='notificatio_recipie_d8fd46_idx')],
            },
        ),
    ]
