# Generated by Django 5.2.15 on 2026-06-22 15:00

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.CharField(default=core.models.generate_ulid, editable=False, help_text='ULID (Universally Unique Lexicographically Sortable Identifier)', max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value store for intrinsic properties of this object')),
                ('relations', models.JSONField(blank=True, default=list, help_text='List of relationships to other objects. Format: [{type: str, target_id: str, target_type: str}]')),
                ('verb', models.CharField(help_text='Action type, e.g. voted, verified, listed_item', max_length=50)),
                ('category', models.CharField(blank=True, help_text='Feed category for icon/grouping (governance/social/market/contracts/…)', max_length=30)),
                ('object_id', models.CharField(blank=True, default='', max_length=26)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, help_text='Deep link to the source object', max_length=500)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Structured payload (object ids, …)')),
                ('actor', models.ForeignKey(help_text='Account that performed the action', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', '-created_at'], name='activities_actor_i_8dd0d9_idx'), models.Index(fields=['actor', 'category'], name='activities_actor_i_8e3727_idx'), models.Index(fields=['content_type', 'object_id'], name='activities_content_cade72_idx')],
            },
        ),
    ]
